// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/account_api_key.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/account_api_key.proto.
 */
export const file_model_relay_account_api_key: GenFile = /*@__PURE__*/
  fileDesc("CiFtb2RlbC9yZWxheS9hY2NvdW50X2FwaV9rZXkucHJvdG8SBXJlbGF5IoIDCg1BY2NvdW50QXBpS2V5EgoKAmlkGAEgASgDEhIKCmFjY291bnRfaWQYAiABKAMSFAoMYWNjb3VudF9uYW1lGAMgASgJEhAKCGtleV9uYW1lGAQgASgJEgsKA2tleRgFIAEoCRIOCgZzdGF0dXMYBiABKAkSDQoFc2NvcGUYByABKAkSEwoLcXVvdGVfbGltaXQYCCABKAMSEgoKcXVvdGVfdXNlZBgJIAEoAxISCgpyYXRlX2xpbWl0GAogASgDEjAKDGxhc3RfdXNlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZXhwaXJlZF9hdBgMIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKY3JlYXRlZF9hdBgNIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgOIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCNlo0Z2l0aHViLmNvbS9tb2RlbGdhdGUvbW9kZWxnYXRlL3BrZy9wcm90by9tb2RlbC9yZWxheWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.AccountApiKey
 */
export type AccountApiKey = Message<"relay.AccountApiKey"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 account_id = 2;
   */
  accountId: bigint;

  /**
   * @generated from field: string account_name = 3;
   */
  accountName: string;

  /**
   * @generated from field: string key_name = 4;
   */
  keyName: string;

  /**
   * @generated from field: string key = 5;
   */
  key: string;

  /**
   * @generated from field: string status = 6;
   */
  status: string;

  /**
   * @generated from field: string scope = 7;
   */
  scope: string;

  /**
   * @generated from field: int64 quote_limit = 8;
   */
  quoteLimit: bigint;

  /**
   * @generated from field: int64 quote_used = 9;
   */
  quoteUsed: bigint;

  /**
   * @generated from field: int64 rate_limit = 10;
   */
  rateLimit: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 11;
   */
  lastUsedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expired_at = 12;
   */
  expiredAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 13;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 14;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.AccountApiKey.
 * Use `create(AccountApiKeySchema)` to create a new message.
 */
export const AccountApiKeySchema: GenMessage<AccountApiKey> = /*@__PURE__*/
  messageDesc(file_model_relay_account_api_key, 0);

