// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/accout.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/accout.proto.
 */
export const file_model_relay_accout: GenFile = /*@__PURE__*/
  fileDesc("Chhtb2RlbC9yZWxheS9hY2NvdXQucHJvdG8SBXJlbGF5IrYBCgdBY2NvdW50EgoKAmlkGAEgASgDEhAKCG5pY2tuYW1lGAIgASgJEgwKBG5hbWUYAyABKAkSDwoHYmFsYW5jZRgEIAEoAxIOCgZzdGF0dXMYBSABKAkSLgoKY3JlYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCNlo0Z2l0aHViLmNvbS9tb2RlbGdhdGUvbW9kZWxnYXRlL3BrZy9wcm90by9tb2RlbC9yZWxheWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.Account
 */
export type Account = Message<"relay.Account"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: int64 balance = 4;
   */
  balance: bigint;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/
  messageDesc(file_model_relay_accout, 0);

