// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/ledger.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/ledger.proto.
 */
export const file_model_relay_ledger: GenFile = /*@__PURE__*/
  fileDesc("Chhtb2RlbC9yZWxheS9sZWRnZXIucHJvdG8SBXJlbGF5ItsBCgZMZWRnZXISCgoCaWQYASABKAMSEgoKYWNjb3VudF9pZBgCIAEoAxIUCgxhY2NvdW50X25hbWUYAyABKAkSEgoKbW9kZWxfY29kZRgEIAEoCRIMCgR0eXBlGAUgASgJEg4KBmFtb3VudBgGIAEoAxIVCg1iYWxhbmNlX2FmdGVyGAcgASgDEhIKCnJlcXVlc3RfaWQYCCABKAMSDgoGcmVhc29uGAkgASgJEi4KCmNyZWF0ZWRfYXQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQjZaNGdpdGh1Yi5jb20vbW9kZWxnYXRlL21vZGVsZ2F0ZS9wa2cvcHJvdG8vbW9kZWwvcmVsYXliBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.Ledger
 */
export type Ledger = Message<"relay.Ledger"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 account_id = 2;
   */
  accountId: bigint;

  /**
   * @generated from field: string account_name = 3;
   */
  accountName: string;

  /**
   * @generated from field: string model_code = 4;
   */
  modelCode: string;

  /**
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * @generated from field: int64 amount = 6;
   */
  amount: bigint;

  /**
   * @generated from field: int64 balance_after = 7;
   */
  balanceAfter: bigint;

  /**
   * @generated from field: int64 request_id = 8;
   */
  requestId: bigint;

  /**
   * @generated from field: string reason = 9;
   */
  reason: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message relay.Ledger.
 * Use `create(LedgerSchema)` to create a new message.
 */
export const LedgerSchema: GenMessage<Ledger> = /*@__PURE__*/
  messageDesc(file_model_relay_ledger, 0);

