// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/model.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/model.proto.
 */
export const file_model_relay_model: GenFile = /*@__PURE__*/
  fileDesc("Chdtb2RlbC9yZWxheS9tb2RlbC5wcm90bxIFcmVsYXkiggIKBU1vZGVsEgoKAmlkGAEgASgDEhMKC3Byb3ZpZGVyX2lkGAIgASgDEhUKDXByb3ZpZGVyX2NvZGUYAyABKAkSEwoLYWN0dWFsX2NvZGUYBCABKAkSDAoEY29kZRgFIAEoCRIMCgRuYW1lGAYgASgJEhAKCHByaW9yaXR5GAcgASgDEg4KBndlaWdodBgIIAEoAxIOCgZzdGF0dXMYCSABKAkSLgoKY3JlYXRlZF9hdBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqfQoLTW9kZWxTdGF0dXMSHAoYTU9ERUxfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUTU9ERUxfU1RBVFVTX0VOQUJMRUQQARIZChVNT0RFTF9TVEFUVVNfRElTQUJMRUQQAhIbChdNT0RFTF9TVEFUVVNfREVQUkVDQVRFRBADQjZaNGdpdGh1Yi5jb20vbW9kZWxnYXRlL21vZGVsZ2F0ZS9wa2cvcHJvdG8vbW9kZWwvcmVsYXliBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.Model
 */
export type Model = Message<"relay.Model"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 provider_id = 2;
   */
  providerId: bigint;

  /**
   * @generated from field: string provider_code = 3;
   */
  providerCode: string;

  /**
   * @generated from field: string actual_code = 4;
   */
  actualCode: string;

  /**
   * @generated from field: string code = 5;
   */
  code: string;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: int64 priority = 7;
   */
  priority: bigint;

  /**
   * @generated from field: int64 weight = 8;
   */
  weight: bigint;

  /**
   * @generated from field: string status = 9;
   */
  status: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 11;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.Model.
 * Use `create(ModelSchema)` to create a new message.
 */
export const ModelSchema: GenMessage<Model> = /*@__PURE__*/
  messageDesc(file_model_relay_model, 0);

/**
 * @generated from enum relay.ModelStatus
 */
export enum ModelStatus {
  /**
   * @generated from enum value: MODEL_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MODEL_STATUS_ENABLED = 1;
   */
  ENABLED = 1,

  /**
   * @generated from enum value: MODEL_STATUS_DISABLED = 2;
   */
  DISABLED = 2,

  /**
   * @generated from enum value: MODEL_STATUS_DEPRECATED = 3;
   */
  DEPRECATED = 3,
}

/**
 * Describes the enum relay.ModelStatus.
 */
export const ModelStatusSchema: GenEnum<ModelStatus> = /*@__PURE__*/
  enumDesc(file_model_relay_model, 0);

