// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/relay_hourly_usage.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/relay_hourly_usage.proto.
 */
export const file_model_relay_relay_hourly_usage: GenFile = /*@__PURE__*/
  fileDesc("CiRtb2RlbC9yZWxheS9yZWxheV9ob3VybHlfdXNhZ2UucHJvdG8SBXJlbGF5IpgCChBSZWxheUhvdXJseVVzYWdlEgoKAmlkGAEgASgDEigKBHRpbWUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhUKDXByb3ZpZGVyX2NvZGUYAyABKAkSFQoNdG90YWxfcmVxdWVzdBgEIAEoAxIVCg10b3RhbF9zdWNjZXNzGAUgASgDEhQKDHRvdGFsX2ZhaWxlZBgGIAEoAxITCgt0b3RhbF9wb2ludBgHIAEoAxIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEI2WjRnaXRodWIuY29tL21vZGVsZ2F0ZS9tb2RlbGdhdGUvcGtnL3Byb3RvL21vZGVsL3JlbGF5YgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.RelayHourlyUsage
 */
export type RelayHourlyUsage = Message<"relay.RelayHourlyUsage"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp time = 2;
   */
  time?: Timestamp;

  /**
   * @generated from field: string provider_code = 3;
   */
  providerCode: string;

  /**
   * @generated from field: int64 total_request = 4;
   */
  totalRequest: bigint;

  /**
   * @generated from field: int64 total_success = 5;
   */
  totalSuccess: bigint;

  /**
   * @generated from field: int64 total_failed = 6;
   */
  totalFailed: bigint;

  /**
   * @generated from field: int64 total_point = 7;
   */
  totalPoint: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.RelayHourlyUsage.
 * Use `create(RelayHourlyUsageSchema)` to create a new message.
 */
export const RelayHourlyUsageSchema: GenMessage<RelayHourlyUsage> = /*@__PURE__*/
  messageDesc(file_model_relay_relay_hourly_usage, 0);

