// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/request.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/request.proto.
 */
export const file_model_relay_request: GenFile = /*@__PURE__*/
  fileDesc("Chltb2RlbC9yZWxheS9yZXF1ZXN0LnByb3RvEgVyZWxheSKhBAoHUmVxdWVzdBIKCgJpZBgBIAEoAxIUCgxyZXF1ZXN0X3V1aWQYAiABKAkSEwoLcHJvdmlkZXJfaWQYAyABKAMSFQoNcHJvdmlkZXJfY29kZRgEIAEoCRIbChNwcm92aWRlcl9hcGlfa2V5X2lkGAUgASgDEhAKCG1vZGVsX2lkGAYgASgDEhIKCm1vZGVsX2NvZGUYByABKAkSFAoMYWN0dWFsX21vZGVsGAggASgJEhIKCmFjY291bnRfaWQYCSABKAMSFAoMYWNjb3VudF9uYW1lGAogASgJEhoKEmFjY291bnRfYXBpX2tleV9pZBgLIAEoAxIVCg1wcm9tcHRfdG9rZW5zGAwgASgDEhkKEWNvbXBsZXRpb25fdG9rZW5zGA0gASgDEhQKDHRvdGFsX3Rva2VucxgOIAEoAxIOCgZzdGF0dXMYDyABKAkSFAoMZWxhcHNlZF90aW1lGBAgASgDEhIKCmVycm9yX2NvZGUYESABKAMSFQoNZXJyb3JfbWVzc2FnZRgSIAEoCRIwCgxjb21wbGV0ZWRfYXQYEyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmNyZWF0ZWRfYXQYFCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYFSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQjZaNGdpdGh1Yi5jb20vbW9kZWxnYXRlL21vZGVsZ2F0ZS9wa2cvcHJvdG8vbW9kZWwvcmVsYXliBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.Request
 */
export type Request = Message<"relay.Request"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string request_uuid = 2;
   */
  requestUuid: string;

  /**
   * @generated from field: int64 provider_id = 3;
   */
  providerId: bigint;

  /**
   * @generated from field: string provider_code = 4;
   */
  providerCode: string;

  /**
   * @generated from field: int64 provider_api_key_id = 5;
   */
  providerApiKeyId: bigint;

  /**
   * @generated from field: int64 model_id = 6;
   */
  modelId: bigint;

  /**
   * @generated from field: string model_code = 7;
   */
  modelCode: string;

  /**
   * @generated from field: string actual_model = 8;
   */
  actualModel: string;

  /**
   * @generated from field: int64 account_id = 9;
   */
  accountId: bigint;

  /**
   * @generated from field: string account_name = 10;
   */
  accountName: string;

  /**
   * @generated from field: int64 account_api_key_id = 11;
   */
  accountApiKeyId: bigint;

  /**
   * @generated from field: int64 prompt_tokens = 12;
   */
  promptTokens: bigint;

  /**
   * @generated from field: int64 completion_tokens = 13;
   */
  completionTokens: bigint;

  /**
   * @generated from field: int64 total_tokens = 14;
   */
  totalTokens: bigint;

  /**
   * @generated from field: string status = 15;
   */
  status: string;

  /**
   * @generated from field: int64 elapsed_time = 16;
   */
  elapsedTime: bigint;

  /**
   * @generated from field: int64 error_code = 17;
   */
  errorCode: bigint;

  /**
   * @generated from field: string error_message = 18;
   */
  errorMessage: string;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 19;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 20;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 21;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/
  messageDesc(file_model_relay_request, 0);

