// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/relay/request_attempt.proto (package relay, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/relay/request_attempt.proto.
 */
export const file_model_relay_request_attempt: GenFile = /*@__PURE__*/
  fileDesc("CiFtb2RlbC9yZWxheS9yZXF1ZXN0X2F0dGVtcHQucHJvdG8SBXJlbGF5IrwECg5SZXF1ZXN0QXR0ZW1wdBIKCgJpZBgBIAEoAxIUCgxyZXF1ZXN0X3V1aWQYAiABKAkSEgoKYXR0ZW1wdF9ubxgDIAEoAxITCgtwcm92aWRlcl9pZBgEIAEoAxIVCg1wcm92aWRlcl9jb2RlGAUgASgJEhsKE3Byb3ZpZGVyX2FwaV9rZXlfaWQYBiABKAMSEAoIbW9kZWxfaWQYByABKAMSEgoKbW9kZWxfY29kZRgIIAEoCRIUCgxhY3R1YWxfbW9kZWwYCSABKAkSEgoKYWNjb3VudF9pZBgKIAEoAxIUCgxhY2NvdW50X25hbWUYCyABKAkSGgoSYWNjb3VudF9hcGlfa2V5X2lkGAwgASgDEhUKDXByb21wdF90b2tlbnMYDSABKAMSGQoRY29tcGxldGlvbl90b2tlbnMYDiABKAMSFAoMdG90YWxfdG9rZW5zGA8gASgDEg4KBnN0YXR1cxgQIAEoCRIUCgxlbGFwc2VkX3RpbWUYESABKAMSEgoKZXJyb3JfY29kZRgSIAEoAxIVCg1lcnJvcl9tZXNzYWdlGBMgASgJEjAKDGNvbXBsZXRlZF9hdBgUIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKY3JlYXRlZF9hdBgVIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgWIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCNlo0Z2l0aHViLmNvbS9tb2RlbGdhdGUvbW9kZWxnYXRlL3BrZy9wcm90by9tb2RlbC9yZWxheWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message relay.RequestAttempt
 */
export type RequestAttempt = Message<"relay.RequestAttempt"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string request_uuid = 2;
   */
  requestUuid: string;

  /**
   * @generated from field: int64 attempt_no = 3;
   */
  attemptNo: bigint;

  /**
   * @generated from field: int64 provider_id = 4;
   */
  providerId: bigint;

  /**
   * @generated from field: string provider_code = 5;
   */
  providerCode: string;

  /**
   * @generated from field: int64 provider_api_key_id = 6;
   */
  providerApiKeyId: bigint;

  /**
   * @generated from field: int64 model_id = 7;
   */
  modelId: bigint;

  /**
   * @generated from field: string model_code = 8;
   */
  modelCode: string;

  /**
   * @generated from field: string actual_model = 9;
   */
  actualModel: string;

  /**
   * @generated from field: int64 account_id = 10;
   */
  accountId: bigint;

  /**
   * @generated from field: string account_name = 11;
   */
  accountName: string;

  /**
   * @generated from field: int64 account_api_key_id = 12;
   */
  accountApiKeyId: bigint;

  /**
   * @generated from field: int64 prompt_tokens = 13;
   */
  promptTokens: bigint;

  /**
   * @generated from field: int64 completion_tokens = 14;
   */
  completionTokens: bigint;

  /**
   * @generated from field: int64 total_tokens = 15;
   */
  totalTokens: bigint;

  /**
   * @generated from field: string status = 16;
   */
  status: string;

  /**
   * @generated from field: int64 elapsed_time = 17;
   */
  elapsedTime: bigint;

  /**
   * @generated from field: int64 error_code = 18;
   */
  errorCode: bigint;

  /**
   * @generated from field: string error_message = 19;
   */
  errorMessage: string;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 20;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 21;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 22;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message relay.RequestAttempt.
 * Use `create(RequestAttemptSchema)` to create a new message.
 */
export const RequestAttemptSchema: GenMessage<RequestAttempt> = /*@__PURE__*/
  messageDesc(file_model_relay_request_attempt, 0);

