// Code generated by MockGen. DO NOT EDIT.
// Source: dao.go
//
// Generated by this command:
//
//	mockgen -source dao.go -destination ./dao_mock.go -package relay
//

// Package relay is a generated GoMock package.
package relay

import (
	context "context"
	reflect "reflect"

	model "github.com/modelgate/modelgate/internal/relay/model"
	db "github.com/modelgate/modelgate/pkg/db"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestDAO is a mock of RequestDAO interface.
type MockRequestDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRequestDAOMockRecorder
	isgomock struct{}
}

// MockRequestDAOMockRecorder is the mock recorder for MockRequestDAO.
type MockRequestDAOMockRecorder struct {
	mock *MockRequestDAO
}

// NewMockRequestDAO creates a new mock instance.
func NewMockRequestDAO(ctrl *gomock.Controller) *MockRequestDAO {
	mock := &MockRequestDAO{ctrl: ctrl}
	mock.recorder = &MockRequestDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestDAO) EXPECT() *MockRequestDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRequestDAO) Count(ctx context.Context, f *model.RequestFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRequestDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRequestDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockRequestDAO) Create(ctx context.Context, m *model.Request) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRequestDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRequestDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockRequestDAO) Delete(ctx context.Context, filter *model.RequestFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRequestDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRequestDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockRequestDAO) Find(ctx context.Context, f *model.RequestFilter, opts ...db.Option) ([]*model.Request, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRequestDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRequestDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockRequestDAO) FindOne(ctx context.Context, f *model.RequestFilter, opts ...db.Option) (*model.Request, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRequestDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRequestDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockRequestDAO) FindOneByID(ctx context.Context, id int64) (*model.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockRequestDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockRequestDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockRequestDAO) Save(ctx context.Context, m *model.Request) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRequestDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRequestDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockRequestDAO) Update(ctx context.Context, filter *model.RequestFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRequestDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRequestDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockRequestDAO) UpdateOne(ctx context.Context, m *model.Request, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockRequestDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRequestDAO)(nil).UpdateOne), ctx, m, update)
}

// MockRequestAttemptDAO is a mock of RequestAttemptDAO interface.
type MockRequestAttemptDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRequestAttemptDAOMockRecorder
	isgomock struct{}
}

// MockRequestAttemptDAOMockRecorder is the mock recorder for MockRequestAttemptDAO.
type MockRequestAttemptDAOMockRecorder struct {
	mock *MockRequestAttemptDAO
}

// NewMockRequestAttemptDAO creates a new mock instance.
func NewMockRequestAttemptDAO(ctrl *gomock.Controller) *MockRequestAttemptDAO {
	mock := &MockRequestAttemptDAO{ctrl: ctrl}
	mock.recorder = &MockRequestAttemptDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestAttemptDAO) EXPECT() *MockRequestAttemptDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRequestAttemptDAO) Count(ctx context.Context, f *model.RequestAttemptFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRequestAttemptDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockRequestAttemptDAO) Create(ctx context.Context, m *model.RequestAttempt) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRequestAttemptDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockRequestAttemptDAO) Delete(ctx context.Context, filter *model.RequestAttemptFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRequestAttemptDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockRequestAttemptDAO) Find(ctx context.Context, f *model.RequestAttemptFilter, opts ...db.Option) ([]*model.RequestAttempt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.RequestAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRequestAttemptDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockRequestAttemptDAO) FindOne(ctx context.Context, f *model.RequestAttemptFilter, opts ...db.Option) (*model.RequestAttempt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.RequestAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRequestAttemptDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRequestAttemptDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockRequestAttemptDAO) FindOneByID(ctx context.Context, id int64) (*model.RequestAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.RequestAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockRequestAttemptDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockRequestAttemptDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockRequestAttemptDAO) Save(ctx context.Context, m *model.RequestAttempt) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRequestAttemptDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockRequestAttemptDAO) Update(ctx context.Context, filter *model.RequestAttemptFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRequestAttemptDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRequestAttemptDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockRequestAttemptDAO) UpdateOne(ctx context.Context, m *model.RequestAttempt, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockRequestAttemptDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRequestAttemptDAO)(nil).UpdateOne), ctx, m, update)
}

// MockProviderDAO is a mock of ProviderDAO interface.
type MockProviderDAO struct {
	ctrl     *gomock.Controller
	recorder *MockProviderDAOMockRecorder
	isgomock struct{}
}

// MockProviderDAOMockRecorder is the mock recorder for MockProviderDAO.
type MockProviderDAOMockRecorder struct {
	mock *MockProviderDAO
}

// NewMockProviderDAO creates a new mock instance.
func NewMockProviderDAO(ctrl *gomock.Controller) *MockProviderDAO {
	mock := &MockProviderDAO{ctrl: ctrl}
	mock.recorder = &MockProviderDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderDAO) EXPECT() *MockProviderDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockProviderDAO) Count(ctx context.Context, f *model.ProviderFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProviderDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProviderDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockProviderDAO) Create(ctx context.Context, m *model.Provider) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProviderDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockProviderDAO) Delete(ctx context.Context, filter *model.ProviderFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProviderDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProviderDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockProviderDAO) Find(ctx context.Context, f *model.ProviderFilter, opts ...db.Option) ([]*model.Provider, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProviderDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProviderDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockProviderDAO) FindOne(ctx context.Context, f *model.ProviderFilter, opts ...db.Option) (*model.Provider, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockProviderDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockProviderDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockProviderDAO) FindOneByID(ctx context.Context, id int64) (*model.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockProviderDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockProviderDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockProviderDAO) Save(ctx context.Context, m *model.Provider) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProviderDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProviderDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockProviderDAO) Update(ctx context.Context, filter *model.ProviderFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProviderDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProviderDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockProviderDAO) UpdateOne(ctx context.Context, m *model.Provider, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockProviderDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockProviderDAO)(nil).UpdateOne), ctx, m, update)
}

// MockProviderApiKeyDAO is a mock of ProviderApiKeyDAO interface.
type MockProviderApiKeyDAO struct {
	ctrl     *gomock.Controller
	recorder *MockProviderApiKeyDAOMockRecorder
	isgomock struct{}
}

// MockProviderApiKeyDAOMockRecorder is the mock recorder for MockProviderApiKeyDAO.
type MockProviderApiKeyDAOMockRecorder struct {
	mock *MockProviderApiKeyDAO
}

// NewMockProviderApiKeyDAO creates a new mock instance.
func NewMockProviderApiKeyDAO(ctrl *gomock.Controller) *MockProviderApiKeyDAO {
	mock := &MockProviderApiKeyDAO{ctrl: ctrl}
	mock.recorder = &MockProviderApiKeyDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderApiKeyDAO) EXPECT() *MockProviderApiKeyDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockProviderApiKeyDAO) Count(ctx context.Context, f *model.ProviderApiKeyFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProviderApiKeyDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockProviderApiKeyDAO) Create(ctx context.Context, m *model.ProviderApiKey) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProviderApiKeyDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockProviderApiKeyDAO) Delete(ctx context.Context, filter *model.ProviderApiKeyFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProviderApiKeyDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockProviderApiKeyDAO) Find(ctx context.Context, f *model.ProviderApiKeyFilter, opts ...db.Option) ([]*model.ProviderApiKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.ProviderApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockProviderApiKeyDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockProviderApiKeyDAO) FindOne(ctx context.Context, f *model.ProviderApiKeyFilter, opts ...db.Option) (*model.ProviderApiKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.ProviderApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockProviderApiKeyDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockProviderApiKeyDAO) FindOneByID(ctx context.Context, id int64) (*model.ProviderApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.ProviderApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockProviderApiKeyDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockProviderApiKeyDAO) Save(ctx context.Context, m *model.ProviderApiKey) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProviderApiKeyDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockProviderApiKeyDAO) Update(ctx context.Context, filter *model.ProviderApiKeyFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProviderApiKeyDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockProviderApiKeyDAO) UpdateOne(ctx context.Context, m *model.ProviderApiKey, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockProviderApiKeyDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockProviderApiKeyDAO)(nil).UpdateOne), ctx, m, update)
}

// MockAccountApiKeyDAO is a mock of AccountApiKeyDAO interface.
type MockAccountApiKeyDAO struct {
	ctrl     *gomock.Controller
	recorder *MockAccountApiKeyDAOMockRecorder
	isgomock struct{}
}

// MockAccountApiKeyDAOMockRecorder is the mock recorder for MockAccountApiKeyDAO.
type MockAccountApiKeyDAOMockRecorder struct {
	mock *MockAccountApiKeyDAO
}

// NewMockAccountApiKeyDAO creates a new mock instance.
func NewMockAccountApiKeyDAO(ctrl *gomock.Controller) *MockAccountApiKeyDAO {
	mock := &MockAccountApiKeyDAO{ctrl: ctrl}
	mock.recorder = &MockAccountApiKeyDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountApiKeyDAO) EXPECT() *MockAccountApiKeyDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockAccountApiKeyDAO) Count(ctx context.Context, f *model.AccountApiKeyFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAccountApiKeyDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockAccountApiKeyDAO) Create(ctx context.Context, m *model.AccountApiKey) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountApiKeyDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockAccountApiKeyDAO) Delete(ctx context.Context, filter *model.AccountApiKeyFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountApiKeyDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockAccountApiKeyDAO) Find(ctx context.Context, f *model.AccountApiKeyFilter, opts ...db.Option) ([]*model.AccountApiKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.AccountApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAccountApiKeyDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockAccountApiKeyDAO) FindOne(ctx context.Context, f *model.AccountApiKeyFilter, opts ...db.Option) (*model.AccountApiKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.AccountApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockAccountApiKeyDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockAccountApiKeyDAO) FindOneByID(ctx context.Context, id int64) (*model.AccountApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.AccountApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockAccountApiKeyDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockAccountApiKeyDAO) Save(ctx context.Context, m *model.AccountApiKey) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccountApiKeyDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockAccountApiKeyDAO) Update(ctx context.Context, filter *model.AccountApiKeyFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountApiKeyDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockAccountApiKeyDAO) UpdateOne(ctx context.Context, m *model.AccountApiKey, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockAccountApiKeyDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockAccountApiKeyDAO)(nil).UpdateOne), ctx, m, update)
}

// MockModelPricingDAO is a mock of ModelPricingDAO interface.
type MockModelPricingDAO struct {
	ctrl     *gomock.Controller
	recorder *MockModelPricingDAOMockRecorder
	isgomock struct{}
}

// MockModelPricingDAOMockRecorder is the mock recorder for MockModelPricingDAO.
type MockModelPricingDAOMockRecorder struct {
	mock *MockModelPricingDAO
}

// NewMockModelPricingDAO creates a new mock instance.
func NewMockModelPricingDAO(ctrl *gomock.Controller) *MockModelPricingDAO {
	mock := &MockModelPricingDAO{ctrl: ctrl}
	mock.recorder = &MockModelPricingDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelPricingDAO) EXPECT() *MockModelPricingDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockModelPricingDAO) Count(ctx context.Context, f *model.ModelPricingFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockModelPricingDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockModelPricingDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockModelPricingDAO) Create(ctx context.Context, m *model.ModelPricing) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockModelPricingDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModelPricingDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockModelPricingDAO) Delete(ctx context.Context, filter *model.ModelPricingFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockModelPricingDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModelPricingDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockModelPricingDAO) Find(ctx context.Context, f *model.ModelPricingFilter, opts ...db.Option) ([]*model.ModelPricing, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.ModelPricing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockModelPricingDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockModelPricingDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockModelPricingDAO) FindOne(ctx context.Context, f *model.ModelPricingFilter, opts ...db.Option) (*model.ModelPricing, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.ModelPricing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockModelPricingDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockModelPricingDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockModelPricingDAO) FindOneByID(ctx context.Context, id int64) (*model.ModelPricing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.ModelPricing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockModelPricingDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockModelPricingDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockModelPricingDAO) Save(ctx context.Context, m *model.ModelPricing) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockModelPricingDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockModelPricingDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockModelPricingDAO) Update(ctx context.Context, filter *model.ModelPricingFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockModelPricingDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModelPricingDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockModelPricingDAO) UpdateOne(ctx context.Context, m *model.ModelPricing, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockModelPricingDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockModelPricingDAO)(nil).UpdateOne), ctx, m, update)
}

// MockModelDAO is a mock of ModelDAO interface.
type MockModelDAO struct {
	ctrl     *gomock.Controller
	recorder *MockModelDAOMockRecorder
	isgomock struct{}
}

// MockModelDAOMockRecorder is the mock recorder for MockModelDAO.
type MockModelDAOMockRecorder struct {
	mock *MockModelDAO
}

// NewMockModelDAO creates a new mock instance.
func NewMockModelDAO(ctrl *gomock.Controller) *MockModelDAO {
	mock := &MockModelDAO{ctrl: ctrl}
	mock.recorder = &MockModelDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelDAO) EXPECT() *MockModelDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockModelDAO) Count(ctx context.Context, f *model.ModelFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockModelDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockModelDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockModelDAO) Create(ctx context.Context, m *model.Model) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockModelDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockModelDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockModelDAO) Delete(ctx context.Context, filter *model.ModelFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockModelDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockModelDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockModelDAO) Find(ctx context.Context, f *model.ModelFilter, opts ...db.Option) ([]*model.Model, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockModelDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockModelDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockModelDAO) FindOne(ctx context.Context, f *model.ModelFilter, opts ...db.Option) (*model.Model, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockModelDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockModelDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockModelDAO) FindOneByID(ctx context.Context, id int64) (*model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockModelDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockModelDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockModelDAO) Save(ctx context.Context, m *model.Model) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockModelDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockModelDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockModelDAO) Update(ctx context.Context, filter *model.ModelFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockModelDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModelDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockModelDAO) UpdateOne(ctx context.Context, m *model.Model, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockModelDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockModelDAO)(nil).UpdateOne), ctx, m, update)
}

// MockAccountDAO is a mock of AccountDAO interface.
type MockAccountDAO struct {
	ctrl     *gomock.Controller
	recorder *MockAccountDAOMockRecorder
	isgomock struct{}
}

// MockAccountDAOMockRecorder is the mock recorder for MockAccountDAO.
type MockAccountDAOMockRecorder struct {
	mock *MockAccountDAO
}

// NewMockAccountDAO creates a new mock instance.
func NewMockAccountDAO(ctrl *gomock.Controller) *MockAccountDAO {
	mock := &MockAccountDAO{ctrl: ctrl}
	mock.recorder = &MockAccountDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountDAO) EXPECT() *MockAccountDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockAccountDAO) Count(ctx context.Context, f *model.AccountFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAccountDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAccountDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockAccountDAO) Create(ctx context.Context, m *model.Account) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountDAO)(nil).Create), ctx, m)
}

// DeductBalance mocks base method.
func (m *MockAccountDAO) DeductBalance(ctx context.Context, accountId, amount, requestId int64, typ model.LedgerType, reason string) (*model.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductBalance", ctx, accountId, amount, requestId, typ, reason)
	ret0, _ := ret[0].(*model.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductBalance indicates an expected call of DeductBalance.
func (mr *MockAccountDAOMockRecorder) DeductBalance(ctx, accountId, amount, requestId, typ, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductBalance", reflect.TypeOf((*MockAccountDAO)(nil).DeductBalance), ctx, accountId, amount, requestId, typ, reason)
}

// Delete mocks base method.
func (m *MockAccountDAO) Delete(ctx context.Context, filter *model.AccountFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockAccountDAO) Find(ctx context.Context, f *model.AccountFilter, opts ...db.Option) ([]*model.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAccountDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAccountDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockAccountDAO) FindOne(ctx context.Context, f *model.AccountFilter, opts ...db.Option) (*model.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockAccountDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockAccountDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockAccountDAO) FindOneByID(ctx context.Context, id int64) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockAccountDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockAccountDAO)(nil).FindOneByID), ctx, id)
}

// IncreaseBalance mocks base method.
func (m *MockAccountDAO) IncreaseBalance(ctx context.Context, accountId, amount, requestId int64, typ model.LedgerType, reason string) (*model.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", ctx, accountId, amount, requestId, typ, reason)
	ret0, _ := ret[0].(*model.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockAccountDAOMockRecorder) IncreaseBalance(ctx, accountId, amount, requestId, typ, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockAccountDAO)(nil).IncreaseBalance), ctx, accountId, amount, requestId, typ, reason)
}

// Save mocks base method.
func (m_2 *MockAccountDAO) Save(ctx context.Context, m *model.Account) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccountDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockAccountDAO) Update(ctx context.Context, filter *model.AccountFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockAccountDAO) UpdateOne(ctx context.Context, m *model.Account, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockAccountDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockAccountDAO)(nil).UpdateOne), ctx, m, update)
}

// MockLedgerDAO is a mock of LedgerDAO interface.
type MockLedgerDAO struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerDAOMockRecorder
	isgomock struct{}
}

// MockLedgerDAOMockRecorder is the mock recorder for MockLedgerDAO.
type MockLedgerDAOMockRecorder struct {
	mock *MockLedgerDAO
}

// NewMockLedgerDAO creates a new mock instance.
func NewMockLedgerDAO(ctrl *gomock.Controller) *MockLedgerDAO {
	mock := &MockLedgerDAO{ctrl: ctrl}
	mock.recorder = &MockLedgerDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerDAO) EXPECT() *MockLedgerDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockLedgerDAO) Count(ctx context.Context, f *model.LedgerFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockLedgerDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockLedgerDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockLedgerDAO) Create(ctx context.Context, m *model.Ledger) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLedgerDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLedgerDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockLedgerDAO) Delete(ctx context.Context, filter *model.LedgerFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockLedgerDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLedgerDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockLedgerDAO) Find(ctx context.Context, f *model.LedgerFilter, opts ...db.Option) ([]*model.Ledger, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLedgerDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLedgerDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockLedgerDAO) FindOne(ctx context.Context, f *model.LedgerFilter, opts ...db.Option) (*model.Ledger, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockLedgerDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockLedgerDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockLedgerDAO) FindOneByID(ctx context.Context, id int64) (*model.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockLedgerDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockLedgerDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockLedgerDAO) Save(ctx context.Context, m *model.Ledger) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLedgerDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLedgerDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockLedgerDAO) Update(ctx context.Context, filter *model.LedgerFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLedgerDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLedgerDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockLedgerDAO) UpdateOne(ctx context.Context, m *model.Ledger, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockLedgerDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockLedgerDAO)(nil).UpdateOne), ctx, m, update)
}

// MockRelayUsageDAO is a mock of RelayUsageDAO interface.
type MockRelayUsageDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRelayUsageDAOMockRecorder
	isgomock struct{}
}

// MockRelayUsageDAOMockRecorder is the mock recorder for MockRelayUsageDAO.
type MockRelayUsageDAOMockRecorder struct {
	mock *MockRelayUsageDAO
}

// NewMockRelayUsageDAO creates a new mock instance.
func NewMockRelayUsageDAO(ctrl *gomock.Controller) *MockRelayUsageDAO {
	mock := &MockRelayUsageDAO{ctrl: ctrl}
	mock.recorder = &MockRelayUsageDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayUsageDAO) EXPECT() *MockRelayUsageDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRelayUsageDAO) Count(ctx context.Context, f *model.RelayUsageFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRelayUsageDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRelayUsageDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockRelayUsageDAO) Create(ctx context.Context, m *model.RelayUsage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRelayUsageDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRelayUsageDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockRelayUsageDAO) Delete(ctx context.Context, filter *model.RelayUsageFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRelayUsageDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRelayUsageDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockRelayUsageDAO) Find(ctx context.Context, f *model.RelayUsageFilter, opts ...db.Option) ([]*model.RelayUsage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.RelayUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRelayUsageDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRelayUsageDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockRelayUsageDAO) FindOne(ctx context.Context, f *model.RelayUsageFilter, opts ...db.Option) (*model.RelayUsage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.RelayUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRelayUsageDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRelayUsageDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockRelayUsageDAO) FindOneByID(ctx context.Context, id int64) (*model.RelayUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.RelayUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockRelayUsageDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockRelayUsageDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockRelayUsageDAO) Save(ctx context.Context, m *model.RelayUsage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRelayUsageDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRelayUsageDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockRelayUsageDAO) Update(ctx context.Context, filter *model.RelayUsageFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRelayUsageDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRelayUsageDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockRelayUsageDAO) UpdateOne(ctx context.Context, m *model.RelayUsage, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockRelayUsageDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRelayUsageDAO)(nil).UpdateOne), ctx, m, update)
}

// MockRelayHourlyUsageDAO is a mock of RelayHourlyUsageDAO interface.
type MockRelayHourlyUsageDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRelayHourlyUsageDAOMockRecorder
	isgomock struct{}
}

// MockRelayHourlyUsageDAOMockRecorder is the mock recorder for MockRelayHourlyUsageDAO.
type MockRelayHourlyUsageDAOMockRecorder struct {
	mock *MockRelayHourlyUsageDAO
}

// NewMockRelayHourlyUsageDAO creates a new mock instance.
func NewMockRelayHourlyUsageDAO(ctrl *gomock.Controller) *MockRelayHourlyUsageDAO {
	mock := &MockRelayHourlyUsageDAO{ctrl: ctrl}
	mock.recorder = &MockRelayHourlyUsageDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayHourlyUsageDAO) EXPECT() *MockRelayHourlyUsageDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRelayHourlyUsageDAO) Count(ctx context.Context, f *model.RelayHourlyUsageFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Count(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Count), ctx, f)
}

// Create mocks base method.
func (m_2 *MockRelayHourlyUsageDAO) Create(ctx context.Context, m *model.RelayHourlyUsage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockRelayHourlyUsageDAO) Delete(ctx context.Context, filter *model.RelayHourlyUsageFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Delete(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Delete), ctx, filter)
}

// Find mocks base method.
func (m *MockRelayHourlyUsageDAO) Find(ctx context.Context, f *model.RelayHourlyUsageFilter, opts ...db.Option) ([]*model.RelayHourlyUsage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].([]*model.RelayHourlyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Find(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockRelayHourlyUsageDAO) FindOne(ctx context.Context, f *model.RelayHourlyUsageFilter, opts ...db.Option) (*model.RelayHourlyUsage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(*model.RelayHourlyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRelayHourlyUsageDAOMockRecorder) FindOne(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).FindOne), varargs...)
}

// FindOneByID mocks base method.
func (m *MockRelayHourlyUsageDAO) FindOneByID(ctx context.Context, id int64) (*model.RelayHourlyUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByID", ctx, id)
	ret0, _ := ret[0].(*model.RelayHourlyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByID indicates an expected call of FindOneByID.
func (mr *MockRelayHourlyUsageDAOMockRecorder) FindOneByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByID", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).FindOneByID), ctx, id)
}

// Save mocks base method.
func (m_2 *MockRelayHourlyUsageDAO) Save(ctx context.Context, m *model.RelayHourlyUsage) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Save(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Save), ctx, m)
}

// Update mocks base method.
func (m *MockRelayHourlyUsageDAO) Update(ctx context.Context, filter *model.RelayHourlyUsageFilter, update map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter, update)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRelayHourlyUsageDAOMockRecorder) Update(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).Update), ctx, filter, update)
}

// UpdateOne mocks base method.
func (m_2 *MockRelayHourlyUsageDAO) UpdateOne(ctx context.Context, m *model.RelayHourlyUsage, update map[string]any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateOne", ctx, m, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockRelayHourlyUsageDAOMockRecorder) UpdateOne(ctx, m, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRelayHourlyUsageDAO)(nil).UpdateOne), ctx, m, update)
}
