// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file admin/v1/auth.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { UserInfo, UserSchema } from "../../model/system/user_pb";
import { file_model_system_user } from "../../model/system/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/v1/auth.proto.
 */
export const file_admin_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS9hdXRoLnByb3RvEghhZG1pbi52MSIsChNSZWZyZXNoVG9rZW5SZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiQwoUUmVmcmVzaFRva2VuUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkiRwoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhMKC3JlbWVtYmVyX21lGAMgASgIIjwKDUxvZ2luUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkiMwoNU2lnblVwUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIQCg5TaWduT3V0UmVxdWVzdCIUChJHZXRVc2VySW5mb1JlcXVlc3QiNQoTR2V0VXNlckluZm9SZXNwb25zZRIeCgR1c2VyGAEgASgLMhAuc3lzdGVtLlVzZXJJbmZvMtoCCgtBdXRoU2VydmljZRI6CgVMb2dpbhIWLmFkbWluLnYxLkxvZ2luUmVxdWVzdBoXLmFkbWluLnYxLkxvZ2luUmVzcG9uc2UiABJPCgxSZWZyZXNoVG9rZW4SHS5hZG1pbi52MS5SZWZyZXNoVG9rZW5SZXF1ZXN0Gh4uYWRtaW4udjEuUmVmcmVzaFRva2VuUmVzcG9uc2UiABIxCgZTaWduVXASFy5hZG1pbi52MS5TaWduVXBSZXF1ZXN0Ggwuc3lzdGVtLlVzZXIiABI9CgdTaWduT3V0EhguYWRtaW4udjEuU2lnbk91dFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJMCgtHZXRVc2VySW5mbxIcLmFkbWluLnYxLkdldFVzZXJJbmZvUmVxdWVzdBodLmFkbWluLnYxLkdldFVzZXJJbmZvUmVzcG9uc2UiAEIzWjFnaXRodWIuY29tL21vZGVsZ2F0ZS9tb2RlbGdhdGUvcGtnL3Byb3RvL2FkbWluL3YxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_protobuf_empty, file_google_protobuf_timestamp, file_model_system_user]);

/**
 * @generated from message admin.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"admin.v1.RefreshTokenRequest"> & {
  /**
   * The refresh token to refresh.
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message admin.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 0);

/**
 * @generated from message admin.v1.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"admin.v1.RefreshTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;
};

/**
 * Describes the message admin.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 1);

/**
 * @generated from message admin.v1.LoginRequest
 */
export type LoginRequest = Message<"admin.v1.LoginRequest"> & {
  /**
   * The username to sign in with.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password to sign in with.
   *
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * Whether the session should never expire.
   *
   * @generated from field: bool remember_me = 3;
   */
  rememberMe: boolean;
};

/**
 * Describes the message admin.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 2);

/**
 * @generated from message admin.v1.LoginResponse
 */
export type LoginResponse = Message<"admin.v1.LoginResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;
};

/**
 * Describes the message admin.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 3);

/**
 * @generated from message admin.v1.SignUpRequest
 */
export type SignUpRequest = Message<"admin.v1.SignUpRequest"> & {
  /**
   * The username to sign up with.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password to sign up with.
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message admin.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 4);

/**
 * @generated from message admin.v1.SignOutRequest
 */
export type SignOutRequest = Message<"admin.v1.SignOutRequest"> & {
};

/**
 * Describes the message admin.v1.SignOutRequest.
 * Use `create(SignOutRequestSchema)` to create a new message.
 */
export const SignOutRequestSchema: GenMessage<SignOutRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 5);

/**
 * @generated from message admin.v1.GetUserInfoRequest
 */
export type GetUserInfoRequest = Message<"admin.v1.GetUserInfoRequest"> & {
};

/**
 * Describes the message admin.v1.GetUserInfoRequest.
 * Use `create(GetUserInfoRequestSchema)` to create a new message.
 */
export const GetUserInfoRequestSchema: GenMessage<GetUserInfoRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 6);

/**
 * @generated from message admin.v1.GetUserInfoResponse
 */
export type GetUserInfoResponse = Message<"admin.v1.GetUserInfoResponse"> & {
  /**
   * @generated from field: system.UserInfo user = 1;
   */
  user?: UserInfo;
};

/**
 * Describes the message admin.v1.GetUserInfoResponse.
 * Use `create(GetUserInfoResponseSchema)` to create a new message.
 */
export const GetUserInfoResponseSchema: GenMessage<GetUserInfoResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_auth, 7);

/**
 * @generated from service admin.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * Login signs in the user with the given username and password.
   *
   * @generated from rpc admin.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * RefreshToken refreshes the access token.
   *
   * @generated from rpc admin.v1.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
  /**
   * SignUp signs up the user with the given username and password.
   *
   * @generated from rpc admin.v1.AuthService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * SignOut signs out the user.
   *
   * @generated from rpc admin.v1.AuthService.SignOut
   */
  signOut: {
    methodKind: "unary";
    input: typeof SignOutRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * GetUserInfo returns the current auth status of the user.
   *
   * @generated from rpc admin.v1.AuthService.GetUserInfo
   */
  getUserInfo: {
    methodKind: "unary";
    input: typeof GetUserInfoRequestSchema;
    output: typeof GetUserInfoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_v1_auth, 0);

