// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/account_api_key.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	KeyName       string                 `protobuf:"bytes,4,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	QuoteLimit    int64                  `protobuf:"varint,8,opt,name=quote_limit,json=quoteLimit,proto3" json:"quote_limit,omitempty"`
	QuoteUsed     int64                  `protobuf:"varint,9,opt,name=quote_used,json=quoteUsed,proto3" json:"quote_used,omitempty"`
	RateLimit     int64                  `protobuf:"varint,10,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountApiKey) Reset() {
	*x = AccountApiKey{}
	mi := &file_model_relay_account_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiKey) ProtoMessage() {}

func (x *AccountApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_account_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiKey.ProtoReflect.Descriptor instead.
func (*AccountApiKey) Descriptor() ([]byte, []int) {
	return file_model_relay_account_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *AccountApiKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountApiKey) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountApiKey) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountApiKey) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *AccountApiKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AccountApiKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountApiKey) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AccountApiKey) GetQuoteLimit() int64 {
	if x != nil {
		return x.QuoteLimit
	}
	return 0
}

func (x *AccountApiKey) GetQuoteUsed() int64 {
	if x != nil {
		return x.QuoteUsed
	}
	return 0
}

func (x *AccountApiKey) GetRateLimit() int64 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *AccountApiKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *AccountApiKey) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *AccountApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccountApiKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_model_relay_account_api_key_proto protoreflect.FileDescriptor

const file_model_relay_account_api_key_proto_rawDesc = "" +
	"\n" +
	"!model/relay/account_api_key.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x04\n" +
	"\rAccountApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x19\n" +
	"\bkey_name\x18\x04 \x01(\tR\akeyName\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x1f\n" +
	"\vquote_limit\x18\b \x01(\x03R\n" +
	"quoteLimit\x12\x1d\n" +
	"\n" +
	"quote_used\x18\t \x01(\x03R\tquoteUsed\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\n" +
	" \x01(\x03R\trateLimit\x12<\n" +
	"\flast_used_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expired_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_account_api_key_proto_rawDescOnce sync.Once
	file_model_relay_account_api_key_proto_rawDescData []byte
)

func file_model_relay_account_api_key_proto_rawDescGZIP() []byte {
	file_model_relay_account_api_key_proto_rawDescOnce.Do(func() {
		file_model_relay_account_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_account_api_key_proto_rawDesc), len(file_model_relay_account_api_key_proto_rawDesc)))
	})
	return file_model_relay_account_api_key_proto_rawDescData
}

var file_model_relay_account_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_account_api_key_proto_goTypes = []any{
	(*AccountApiKey)(nil),         // 0: relay.AccountApiKey
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_relay_account_api_key_proto_depIdxs = []int32{
	1, // 0: relay.AccountApiKey.last_used_at:type_name -> google.protobuf.Timestamp
	1, // 1: relay.AccountApiKey.expired_at:type_name -> google.protobuf.Timestamp
	1, // 2: relay.AccountApiKey.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: relay.AccountApiKey.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_relay_account_api_key_proto_init() }
func file_model_relay_account_api_key_proto_init() {
	if File_model_relay_account_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_account_api_key_proto_rawDesc), len(file_model_relay_account_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_account_api_key_proto_goTypes,
		DependencyIndexes: file_model_relay_account_api_key_proto_depIdxs,
		MessageInfos:      file_model_relay_account_api_key_proto_msgTypes,
	}.Build()
	File_model_relay_account_api_key_proto = out.File
	file_model_relay_account_api_key_proto_goTypes = nil
	file_model_relay_account_api_key_proto_depIdxs = nil
}
