// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/ledger.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	ModelCode     string                 `protobuf:"bytes,4,opt,name=model_code,json=modelCode,proto3" json:"model_code,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	RequestId     int64                  `protobuf:"varint,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_model_relay_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_model_relay_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Ledger) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ledger) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Ledger) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Ledger) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *Ledger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ledger) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Ledger) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *Ledger) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Ledger) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Ledger) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_model_relay_ledger_proto protoreflect.FileDescriptor

const file_model_relay_ledger_proto_rawDesc = "" +
	"\n" +
	"\x18model/relay/ledger.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\x06Ledger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1d\n" +
	"\n" +
	"model_code\x18\x04 \x01(\tR\tmodelCode\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12#\n" +
	"\rbalance_after\x18\a \x01(\x03R\fbalanceAfter\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\x03R\trequestId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_ledger_proto_rawDescOnce sync.Once
	file_model_relay_ledger_proto_rawDescData []byte
)

func file_model_relay_ledger_proto_rawDescGZIP() []byte {
	file_model_relay_ledger_proto_rawDescOnce.Do(func() {
		file_model_relay_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_ledger_proto_rawDesc), len(file_model_relay_ledger_proto_rawDesc)))
	})
	return file_model_relay_ledger_proto_rawDescData
}

var file_model_relay_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_ledger_proto_goTypes = []any{
	(*Ledger)(nil),                // 0: relay.Ledger
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_relay_ledger_proto_depIdxs = []int32{
	1, // 0: relay.Ledger.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_relay_ledger_proto_init() }
func file_model_relay_ledger_proto_init() {
	if File_model_relay_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_ledger_proto_rawDesc), len(file_model_relay_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_ledger_proto_goTypes,
		DependencyIndexes: file_model_relay_ledger_proto_depIdxs,
		MessageInfos:      file_model_relay_ledger_proto_msgTypes,
	}.Build()
	File_model_relay_ledger_proto = out.File
	file_model_relay_ledger_proto_goTypes = nil
	file_model_relay_ledger_proto_depIdxs = nil
}
