// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/model.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelStatus int32

const (
	ModelStatus_MODEL_STATUS_UNSPECIFIED ModelStatus = 0
	ModelStatus_MODEL_STATUS_ENABLED     ModelStatus = 1
	ModelStatus_MODEL_STATUS_DISABLED    ModelStatus = 2
	ModelStatus_MODEL_STATUS_DEPRECATED  ModelStatus = 3
)

// Enum value maps for ModelStatus.
var (
	ModelStatus_name = map[int32]string{
		0: "MODEL_STATUS_UNSPECIFIED",
		1: "MODEL_STATUS_ENABLED",
		2: "MODEL_STATUS_DISABLED",
		3: "MODEL_STATUS_DEPRECATED",
	}
	ModelStatus_value = map[string]int32{
		"MODEL_STATUS_UNSPECIFIED": 0,
		"MODEL_STATUS_ENABLED":     1,
		"MODEL_STATUS_DISABLED":    2,
		"MODEL_STATUS_DEPRECATED":  3,
	}
)

func (x ModelStatus) Enum() *ModelStatus {
	p := new(ModelStatus)
	*p = x
	return p
}

func (x ModelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_model_relay_model_proto_enumTypes[0].Descriptor()
}

func (ModelStatus) Type() protoreflect.EnumType {
	return &file_model_relay_model_proto_enumTypes[0]
}

func (x ModelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelStatus.Descriptor instead.
func (ModelStatus) EnumDescriptor() ([]byte, []int) {
	return file_model_relay_model_proto_rawDescGZIP(), []int{0}
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId    int64                  `protobuf:"varint,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,3,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	ActualCode    string                 `protobuf:"bytes,4,opt,name=actual_code,json=actualCode,proto3" json:"actual_code,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int64                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        int64                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_model_relay_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_model_relay_model_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *Model) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *Model) GetActualCode() string {
	if x != nil {
		return x.ActualCode
	}
	return ""
}

func (x *Model) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Model) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Model) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_model_relay_model_proto protoreflect.FileDescriptor

const file_model_relay_model_proto_rawDesc = "" +
	"\n" +
	"\x17model/relay/model.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\x03R\n" +
	"providerId\x12#\n" +
	"\rprovider_code\x18\x03 \x01(\tR\fproviderCode\x12\x1f\n" +
	"\vactual_code\x18\x04 \x01(\tR\n" +
	"actualCode\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x03R\bpriority\x12\x16\n" +
	"\x06weight\x18\b \x01(\x03R\x06weight\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*}\n" +
	"\vModelStatus\x12\x1c\n" +
	"\x18MODEL_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MODEL_STATUS_ENABLED\x10\x01\x12\x19\n" +
	"\x15MODEL_STATUS_DISABLED\x10\x02\x12\x1b\n" +
	"\x17MODEL_STATUS_DEPRECATED\x10\x03B6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_model_proto_rawDescOnce sync.Once
	file_model_relay_model_proto_rawDescData []byte
)

func file_model_relay_model_proto_rawDescGZIP() []byte {
	file_model_relay_model_proto_rawDescOnce.Do(func() {
		file_model_relay_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_model_proto_rawDesc), len(file_model_relay_model_proto_rawDesc)))
	})
	return file_model_relay_model_proto_rawDescData
}

var file_model_relay_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_relay_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_model_proto_goTypes = []any{
	(ModelStatus)(0),              // 0: relay.ModelStatus
	(*Model)(nil),                 // 1: relay.Model
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_model_relay_model_proto_depIdxs = []int32{
	2, // 0: relay.Model.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: relay.Model.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_relay_model_proto_init() }
func file_model_relay_model_proto_init() {
	if File_model_relay_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_model_proto_rawDesc), len(file_model_relay_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_model_proto_goTypes,
		DependencyIndexes: file_model_relay_model_proto_depIdxs,
		EnumInfos:         file_model_relay_model_proto_enumTypes,
		MessageInfos:      file_model_relay_model_proto_msgTypes,
	}.Build()
	File_model_relay_model_proto = out.File
	file_model_relay_model_proto_goTypes = nil
	file_model_relay_model_proto_depIdxs = nil
}
