// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/provider_api_key.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId    int64                  `protobuf:"varint,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,3,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Weight        int64                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	FaildCount    int64                  `protobuf:"varint,8,opt,name=faild_count,json=faildCount,proto3" json:"faild_count,omitempty"`
	CoolDownUntil *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=cool_down_until,json=coolDownUntil,proto3" json:"cool_down_until,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderApiKey) Reset() {
	*x = ProviderApiKey{}
	mi := &file_model_relay_provider_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderApiKey) ProtoMessage() {}

func (x *ProviderApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_provider_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderApiKey.ProtoReflect.Descriptor instead.
func (*ProviderApiKey) Descriptor() ([]byte, []int) {
	return file_model_relay_provider_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderApiKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProviderApiKey) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *ProviderApiKey) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *ProviderApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderApiKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProviderApiKey) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProviderApiKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProviderApiKey) GetFaildCount() int64 {
	if x != nil {
		return x.FaildCount
	}
	return 0
}

func (x *ProviderApiKey) GetCoolDownUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CoolDownUntil
	}
	return nil
}

func (x *ProviderApiKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ProviderApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProviderApiKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_model_relay_provider_api_key_proto protoreflect.FileDescriptor

const file_model_relay_provider_api_key_proto_rawDesc = "" +
	"\n" +
	"\"model/relay/provider_api_key.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x03\n" +
	"\x0eProviderApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\x03R\n" +
	"providerId\x12#\n" +
	"\rprovider_code\x18\x03 \x01(\tR\fproviderCode\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x03R\x06weight\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vfaild_count\x18\b \x01(\x03R\n" +
	"faildCount\x12B\n" +
	"\x0fcool_down_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rcoolDownUntil\x12<\n" +
	"\flast_used_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_provider_api_key_proto_rawDescOnce sync.Once
	file_model_relay_provider_api_key_proto_rawDescData []byte
)

func file_model_relay_provider_api_key_proto_rawDescGZIP() []byte {
	file_model_relay_provider_api_key_proto_rawDescOnce.Do(func() {
		file_model_relay_provider_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_provider_api_key_proto_rawDesc), len(file_model_relay_provider_api_key_proto_rawDesc)))
	})
	return file_model_relay_provider_api_key_proto_rawDescData
}

var file_model_relay_provider_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_provider_api_key_proto_goTypes = []any{
	(*ProviderApiKey)(nil),        // 0: relay.ProviderApiKey
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_relay_provider_api_key_proto_depIdxs = []int32{
	1, // 0: relay.ProviderApiKey.cool_down_until:type_name -> google.protobuf.Timestamp
	1, // 1: relay.ProviderApiKey.last_used_at:type_name -> google.protobuf.Timestamp
	1, // 2: relay.ProviderApiKey.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: relay.ProviderApiKey.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_relay_provider_api_key_proto_init() }
func file_model_relay_provider_api_key_proto_init() {
	if File_model_relay_provider_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_provider_api_key_proto_rawDesc), len(file_model_relay_provider_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_provider_api_key_proto_goTypes,
		DependencyIndexes: file_model_relay_provider_api_key_proto_depIdxs,
		MessageInfos:      file_model_relay_provider_api_key_proto_msgTypes,
	}.Build()
	File_model_relay_provider_api_key_proto = out.File
	file_model_relay_provider_api_key_proto_goTypes = nil
	file_model_relay_provider_api_key_proto_depIdxs = nil
}
