// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/relay_hourly_usage.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayHourlyUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	ProviderCode  string                 `protobuf:"bytes,3,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	TotalRequest  int64                  `protobuf:"varint,4,opt,name=total_request,json=totalRequest,proto3" json:"total_request,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,5,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,6,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalPoint    int64                  `protobuf:"varint,7,opt,name=total_point,json=totalPoint,proto3" json:"total_point,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayHourlyUsage) Reset() {
	*x = RelayHourlyUsage{}
	mi := &file_model_relay_relay_hourly_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayHourlyUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayHourlyUsage) ProtoMessage() {}

func (x *RelayHourlyUsage) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_relay_hourly_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayHourlyUsage.ProtoReflect.Descriptor instead.
func (*RelayHourlyUsage) Descriptor() ([]byte, []int) {
	return file_model_relay_relay_hourly_usage_proto_rawDescGZIP(), []int{0}
}

func (x *RelayHourlyUsage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelayHourlyUsage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RelayHourlyUsage) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *RelayHourlyUsage) GetTotalRequest() int64 {
	if x != nil {
		return x.TotalRequest
	}
	return 0
}

func (x *RelayHourlyUsage) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *RelayHourlyUsage) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *RelayHourlyUsage) GetTotalPoint() int64 {
	if x != nil {
		return x.TotalPoint
	}
	return 0
}

func (x *RelayHourlyUsage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RelayHourlyUsage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_model_relay_relay_hourly_usage_proto protoreflect.FileDescriptor

const file_model_relay_relay_hourly_usage_proto_rawDesc = "" +
	"\n" +
	"$model/relay/relay_hourly_usage.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\x10RelayHourlyUsage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12#\n" +
	"\rprovider_code\x18\x03 \x01(\tR\fproviderCode\x12#\n" +
	"\rtotal_request\x18\x04 \x01(\x03R\ftotalRequest\x12#\n" +
	"\rtotal_success\x18\x05 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x06 \x01(\x03R\vtotalFailed\x12\x1f\n" +
	"\vtotal_point\x18\a \x01(\x03R\n" +
	"totalPoint\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_relay_hourly_usage_proto_rawDescOnce sync.Once
	file_model_relay_relay_hourly_usage_proto_rawDescData []byte
)

func file_model_relay_relay_hourly_usage_proto_rawDescGZIP() []byte {
	file_model_relay_relay_hourly_usage_proto_rawDescOnce.Do(func() {
		file_model_relay_relay_hourly_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_relay_hourly_usage_proto_rawDesc), len(file_model_relay_relay_hourly_usage_proto_rawDesc)))
	})
	return file_model_relay_relay_hourly_usage_proto_rawDescData
}

var file_model_relay_relay_hourly_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_relay_hourly_usage_proto_goTypes = []any{
	(*RelayHourlyUsage)(nil),      // 0: relay.RelayHourlyUsage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_relay_relay_hourly_usage_proto_depIdxs = []int32{
	1, // 0: relay.RelayHourlyUsage.time:type_name -> google.protobuf.Timestamp
	1, // 1: relay.RelayHourlyUsage.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: relay.RelayHourlyUsage.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_relay_relay_hourly_usage_proto_init() }
func file_model_relay_relay_hourly_usage_proto_init() {
	if File_model_relay_relay_hourly_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_relay_hourly_usage_proto_rawDesc), len(file_model_relay_relay_hourly_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_relay_hourly_usage_proto_goTypes,
		DependencyIndexes: file_model_relay_relay_hourly_usage_proto_depIdxs,
		MessageInfos:      file_model_relay_relay_hourly_usage_proto_msgTypes,
	}.Build()
	File_model_relay_relay_hourly_usage_proto = out.File
	file_model_relay_relay_hourly_usage_proto_goTypes = nil
	file_model_relay_relay_hourly_usage_proto_depIdxs = nil
}
