// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/relay_usage.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalRequest  int64                  `protobuf:"varint,2,opt,name=total_request,json=totalRequest,proto3" json:"total_request,omitempty"`
	TotalSuccess  int64                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int64                  `protobuf:"varint,4,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalPoint    int64                  `protobuf:"varint,5,opt,name=total_point,json=totalPoint,proto3" json:"total_point,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayUsage) Reset() {
	*x = RelayUsage{}
	mi := &file_model_relay_relay_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUsage) ProtoMessage() {}

func (x *RelayUsage) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_relay_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUsage.ProtoReflect.Descriptor instead.
func (*RelayUsage) Descriptor() ([]byte, []int) {
	return file_model_relay_relay_usage_proto_rawDescGZIP(), []int{0}
}

func (x *RelayUsage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RelayUsage) GetTotalRequest() int64 {
	if x != nil {
		return x.TotalRequest
	}
	return 0
}

func (x *RelayUsage) GetTotalSuccess() int64 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *RelayUsage) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *RelayUsage) GetTotalPoint() int64 {
	if x != nil {
		return x.TotalPoint
	}
	return 0
}

func (x *RelayUsage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RelayUsage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UsageSerie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []*UsageItem           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageSerie) Reset() {
	*x = UsageSerie{}
	mi := &file_model_relay_relay_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSerie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSerie) ProtoMessage() {}

func (x *UsageSerie) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_relay_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSerie.ProtoReflect.Descriptor instead.
func (*UsageSerie) Descriptor() ([]byte, []int) {
	return file_model_relay_relay_usage_proto_rawDescGZIP(), []int{1}
}

func (x *UsageSerie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsageSerie) GetData() []*UsageItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UsageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageItem) Reset() {
	*x = UsageItem{}
	mi := &file_model_relay_relay_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageItem) ProtoMessage() {}

func (x *UsageItem) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_relay_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageItem.ProtoReflect.Descriptor instead.
func (*UsageItem) Descriptor() ([]byte, []int) {
	return file_model_relay_relay_usage_proto_rawDescGZIP(), []int{2}
}

func (x *UsageItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UsageItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_model_relay_relay_usage_proto protoreflect.FileDescriptor

const file_model_relay_relay_usage_proto_rawDesc = "" +
	"\n" +
	"\x1dmodel/relay/relay_usage.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\n" +
	"RelayUsage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rtotal_request\x18\x02 \x01(\x03R\ftotalRequest\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x03R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x04 \x01(\x03R\vtotalFailed\x12\x1f\n" +
	"\vtotal_point\x18\x05 \x01(\x03R\n" +
	"totalPoint\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\n" +
	"UsageSerie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.relay.UsageItemR\x04data\"7\n" +
	"\tUsageItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05valueB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_relay_usage_proto_rawDescOnce sync.Once
	file_model_relay_relay_usage_proto_rawDescData []byte
)

func file_model_relay_relay_usage_proto_rawDescGZIP() []byte {
	file_model_relay_relay_usage_proto_rawDescOnce.Do(func() {
		file_model_relay_relay_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_relay_usage_proto_rawDesc), len(file_model_relay_relay_usage_proto_rawDesc)))
	})
	return file_model_relay_relay_usage_proto_rawDescData
}

var file_model_relay_relay_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_relay_relay_usage_proto_goTypes = []any{
	(*RelayUsage)(nil),            // 0: relay.RelayUsage
	(*UsageSerie)(nil),            // 1: relay.UsageSerie
	(*UsageItem)(nil),             // 2: relay.UsageItem
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_model_relay_relay_usage_proto_depIdxs = []int32{
	3, // 0: relay.RelayUsage.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: relay.RelayUsage.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: relay.UsageSerie.data:type_name -> relay.UsageItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_relay_relay_usage_proto_init() }
func file_model_relay_relay_usage_proto_init() {
	if File_model_relay_relay_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_relay_usage_proto_rawDesc), len(file_model_relay_relay_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_relay_usage_proto_goTypes,
		DependencyIndexes: file_model_relay_relay_usage_proto_depIdxs,
		MessageInfos:      file_model_relay_relay_usage_proto_msgTypes,
	}.Build()
	File_model_relay_relay_usage_proto = out.File
	file_model_relay_relay_usage_proto_goTypes = nil
	file_model_relay_relay_usage_proto_depIdxs = nil
}
