// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/relay/request.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestUuid      string                 `protobuf:"bytes,2,opt,name=request_uuid,json=requestUuid,proto3" json:"request_uuid,omitempty"`
	ProviderId       int64                  `protobuf:"varint,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderCode     string                 `protobuf:"bytes,4,opt,name=provider_code,json=providerCode,proto3" json:"provider_code,omitempty"`
	ProviderApiKeyId int64                  `protobuf:"varint,5,opt,name=provider_api_key_id,json=providerApiKeyId,proto3" json:"provider_api_key_id,omitempty"`
	ModelId          int64                  `protobuf:"varint,6,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelCode        string                 `protobuf:"bytes,7,opt,name=model_code,json=modelCode,proto3" json:"model_code,omitempty"`
	ActualModel      string                 `protobuf:"bytes,8,opt,name=actual_model,json=actualModel,proto3" json:"actual_model,omitempty"`
	AccountId        int64                  `protobuf:"varint,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName      string                 `protobuf:"bytes,10,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountApiKeyId  int64                  `protobuf:"varint,11,opt,name=account_api_key_id,json=accountApiKeyId,proto3" json:"account_api_key_id,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,12,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,13,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,14,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Status           string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	ElapsedTime      int64                  `protobuf:"varint,16,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	ErrorCode        int64                  `protobuf:"varint,17,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,18,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_model_relay_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_model_relay_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_model_relay_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetRequestUuid() string {
	if x != nil {
		return x.RequestUuid
	}
	return ""
}

func (x *Request) GetProviderId() int64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *Request) GetProviderCode() string {
	if x != nil {
		return x.ProviderCode
	}
	return ""
}

func (x *Request) GetProviderApiKeyId() int64 {
	if x != nil {
		return x.ProviderApiKeyId
	}
	return 0
}

func (x *Request) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Request) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *Request) GetActualModel() string {
	if x != nil {
		return x.ActualModel
	}
	return ""
}

func (x *Request) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Request) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Request) GetAccountApiKeyId() int64 {
	if x != nil {
		return x.AccountApiKeyId
	}
	return 0
}

func (x *Request) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Request) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Request) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Request) GetElapsedTime() int64 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

func (x *Request) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Request) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Request) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Request) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Request) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_model_relay_request_proto protoreflect.FileDescriptor

const file_model_relay_request_proto_rawDesc = "" +
	"\n" +
	"\x19model/relay/request.proto\x12\x05relay\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x06\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\frequest_uuid\x18\x02 \x01(\tR\vrequestUuid\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\x03R\n" +
	"providerId\x12#\n" +
	"\rprovider_code\x18\x04 \x01(\tR\fproviderCode\x12-\n" +
	"\x13provider_api_key_id\x18\x05 \x01(\x03R\x10providerApiKeyId\x12\x19\n" +
	"\bmodel_id\x18\x06 \x01(\x03R\amodelId\x12\x1d\n" +
	"\n" +
	"model_code\x18\a \x01(\tR\tmodelCode\x12!\n" +
	"\factual_model\x18\b \x01(\tR\vactualModel\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\x03R\taccountId\x12!\n" +
	"\faccount_name\x18\n" +
	" \x01(\tR\vaccountName\x12+\n" +
	"\x12account_api_key_id\x18\v \x01(\x03R\x0faccountApiKeyId\x12#\n" +
	"\rprompt_tokens\x18\f \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\r \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x0e \x01(\x03R\vtotalTokens\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12!\n" +
	"\felapsed_time\x18\x10 \x01(\x03R\velapsedTime\x12\x1d\n" +
	"\n" +
	"error_code\x18\x11 \x01(\x03R\terrorCode\x12#\n" +
	"\rerror_message\x18\x12 \x01(\tR\ferrorMessage\x12=\n" +
	"\fcompleted_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB6Z4github.com/modelgate/modelgate/pkg/proto/model/relayb\x06proto3"

var (
	file_model_relay_request_proto_rawDescOnce sync.Once
	file_model_relay_request_proto_rawDescData []byte
)

func file_model_relay_request_proto_rawDescGZIP() []byte {
	file_model_relay_request_proto_rawDescOnce.Do(func() {
		file_model_relay_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_relay_request_proto_rawDesc), len(file_model_relay_request_proto_rawDesc)))
	})
	return file_model_relay_request_proto_rawDescData
}

var file_model_relay_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_relay_request_proto_goTypes = []any{
	(*Request)(nil),               // 0: relay.Request
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_relay_request_proto_depIdxs = []int32{
	1, // 0: relay.Request.completed_at:type_name -> google.protobuf.Timestamp
	1, // 1: relay.Request.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: relay.Request.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_relay_request_proto_init() }
func file_model_relay_request_proto_init() {
	if File_model_relay_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_relay_request_proto_rawDesc), len(file_model_relay_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_relay_request_proto_goTypes,
		DependencyIndexes: file_model_relay_request_proto_depIdxs,
		MessageInfos:      file_model_relay_request_proto_msgTypes,
	}.Build()
	File_model_relay_request_proto = out.File
	file_model_relay_request_proto_goTypes = nil
	file_model_relay_request_proto_depIdxs = nil
}
