/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_permission: () => import("@/views/manage/permission/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "relay_model-pricing": () => import("@/views/relay/model-pricing/index.vue"),
  relay_model: () => import("@/views/relay/model/index.vue"),
  "relay_provider-api-key": () => import("@/views/relay/provider-api-key/index.vue"),
  relay_provider: () => import("@/views/relay/provider/index.vue"),
  usage_ledger: () => import("@/views/usage/ledger/index.vue"),
  usage_request: () => import("@/views/usage/request/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  user_account: () => import("@/views/user/account/index.vue"),
  "user_api-key": () => import("@/views/user/api-key/index.vue"),
};
