// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin/v1/relay.proto

package v1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	relay "github.com/modelgate/modelgate/pkg/proto/model/relay"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RelayServiceName is the fully-qualified name of the RelayService service.
	RelayServiceName = "admin.v1.RelayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RelayServiceCreateProviderProcedure is the fully-qualified name of the RelayService's
	// CreateProvider RPC.
	RelayServiceCreateProviderProcedure = "/admin.v1.RelayService/CreateProvider"
	// RelayServiceUpdateProviderProcedure is the fully-qualified name of the RelayService's
	// UpdateProvider RPC.
	RelayServiceUpdateProviderProcedure = "/admin.v1.RelayService/UpdateProvider"
	// RelayServiceDeleteProvidersProcedure is the fully-qualified name of the RelayService's
	// DeleteProviders RPC.
	RelayServiceDeleteProvidersProcedure = "/admin.v1.RelayService/DeleteProviders"
	// RelayServiceGetProviderListProcedure is the fully-qualified name of the RelayService's
	// GetProviderList RPC.
	RelayServiceGetProviderListProcedure = "/admin.v1.RelayService/GetProviderList"
	// RelayServiceGetProviderCodeListProcedure is the fully-qualified name of the RelayService's
	// GetProviderCodeList RPC.
	RelayServiceGetProviderCodeListProcedure = "/admin.v1.RelayService/GetProviderCodeList"
	// RelayServiceCreateModelProcedure is the fully-qualified name of the RelayService's CreateModel
	// RPC.
	RelayServiceCreateModelProcedure = "/admin.v1.RelayService/CreateModel"
	// RelayServiceUpdateModelProcedure is the fully-qualified name of the RelayService's UpdateModel
	// RPC.
	RelayServiceUpdateModelProcedure = "/admin.v1.RelayService/UpdateModel"
	// RelayServiceDeleteModelsProcedure is the fully-qualified name of the RelayService's DeleteModels
	// RPC.
	RelayServiceDeleteModelsProcedure = "/admin.v1.RelayService/DeleteModels"
	// RelayServiceGetModelListProcedure is the fully-qualified name of the RelayService's GetModelList
	// RPC.
	RelayServiceGetModelListProcedure = "/admin.v1.RelayService/GetModelList"
	// RelayServiceCreateProviderApiKeyProcedure is the fully-qualified name of the RelayService's
	// CreateProviderApiKey RPC.
	RelayServiceCreateProviderApiKeyProcedure = "/admin.v1.RelayService/CreateProviderApiKey"
	// RelayServiceUpdateProviderApiKeyProcedure is the fully-qualified name of the RelayService's
	// UpdateProviderApiKey RPC.
	RelayServiceUpdateProviderApiKeyProcedure = "/admin.v1.RelayService/UpdateProviderApiKey"
	// RelayServiceDeleteProviderApiKeysProcedure is the fully-qualified name of the RelayService's
	// DeleteProviderApiKeys RPC.
	RelayServiceDeleteProviderApiKeysProcedure = "/admin.v1.RelayService/DeleteProviderApiKeys"
	// RelayServiceGetProviderApiKeyListProcedure is the fully-qualified name of the RelayService's
	// GetProviderApiKeyList RPC.
	RelayServiceGetProviderApiKeyListProcedure = "/admin.v1.RelayService/GetProviderApiKeyList"
	// RelayServiceCreateModelPricingProcedure is the fully-qualified name of the RelayService's
	// CreateModelPricing RPC.
	RelayServiceCreateModelPricingProcedure = "/admin.v1.RelayService/CreateModelPricing"
	// RelayServiceUpdateModelPricingProcedure is the fully-qualified name of the RelayService's
	// UpdateModelPricing RPC.
	RelayServiceUpdateModelPricingProcedure = "/admin.v1.RelayService/UpdateModelPricing"
	// RelayServiceDeleteModelPricingsProcedure is the fully-qualified name of the RelayService's
	// DeleteModelPricings RPC.
	RelayServiceDeleteModelPricingsProcedure = "/admin.v1.RelayService/DeleteModelPricings"
	// RelayServiceGetModelPricingListProcedure is the fully-qualified name of the RelayService's
	// GetModelPricingList RPC.
	RelayServiceGetModelPricingListProcedure = "/admin.v1.RelayService/GetModelPricingList"
	// RelayServiceCreateLedgerProcedure is the fully-qualified name of the RelayService's CreateLedger
	// RPC.
	RelayServiceCreateLedgerProcedure = "/admin.v1.RelayService/CreateLedger"
	// RelayServiceDeleteLedgersProcedure is the fully-qualified name of the RelayService's
	// DeleteLedgers RPC.
	RelayServiceDeleteLedgersProcedure = "/admin.v1.RelayService/DeleteLedgers"
	// RelayServiceGetLedgerListProcedure is the fully-qualified name of the RelayService's
	// GetLedgerList RPC.
	RelayServiceGetLedgerListProcedure = "/admin.v1.RelayService/GetLedgerList"
	// RelayServiceCreateAccountApiKeyProcedure is the fully-qualified name of the RelayService's
	// CreateAccountApiKey RPC.
	RelayServiceCreateAccountApiKeyProcedure = "/admin.v1.RelayService/CreateAccountApiKey"
	// RelayServiceUpdateAccountApiKeyProcedure is the fully-qualified name of the RelayService's
	// UpdateAccountApiKey RPC.
	RelayServiceUpdateAccountApiKeyProcedure = "/admin.v1.RelayService/UpdateAccountApiKey"
	// RelayServiceDeleteAccountApiKeysProcedure is the fully-qualified name of the RelayService's
	// DeleteAccountApiKeys RPC.
	RelayServiceDeleteAccountApiKeysProcedure = "/admin.v1.RelayService/DeleteAccountApiKeys"
	// RelayServiceGetAccountApiKeyListProcedure is the fully-qualified name of the RelayService's
	// GetAccountApiKeyList RPC.
	RelayServiceGetAccountApiKeyListProcedure = "/admin.v1.RelayService/GetAccountApiKeyList"
	// RelayServiceCreateAccountProcedure is the fully-qualified name of the RelayService's
	// CreateAccount RPC.
	RelayServiceCreateAccountProcedure = "/admin.v1.RelayService/CreateAccount"
	// RelayServiceUpdateAccountProcedure is the fully-qualified name of the RelayService's
	// UpdateAccount RPC.
	RelayServiceUpdateAccountProcedure = "/admin.v1.RelayService/UpdateAccount"
	// RelayServiceDeleteAccountsProcedure is the fully-qualified name of the RelayService's
	// DeleteAccounts RPC.
	RelayServiceDeleteAccountsProcedure = "/admin.v1.RelayService/DeleteAccounts"
	// RelayServiceGetAccountListProcedure is the fully-qualified name of the RelayService's
	// GetAccountList RPC.
	RelayServiceGetAccountListProcedure = "/admin.v1.RelayService/GetAccountList"
	// RelayServiceGetRequestListProcedure is the fully-qualified name of the RelayService's
	// GetRequestList RPC.
	RelayServiceGetRequestListProcedure = "/admin.v1.RelayService/GetRequestList"
	// RelayServiceDeleteRequestsProcedure is the fully-qualified name of the RelayService's
	// DeleteRequests RPC.
	RelayServiceDeleteRequestsProcedure = "/admin.v1.RelayService/DeleteRequests"
	// RelayServiceGetRelayInfoProcedure is the fully-qualified name of the RelayService's GetRelayInfo
	// RPC.
	RelayServiceGetRelayInfoProcedure = "/admin.v1.RelayService/GetRelayInfo"
	// RelayServiceGetTotalRelayUsageProcedure is the fully-qualified name of the RelayService's
	// GetTotalRelayUsage RPC.
	RelayServiceGetTotalRelayUsageProcedure = "/admin.v1.RelayService/GetTotalRelayUsage"
	// RelayServiceGetRelayUsageProcedure is the fully-qualified name of the RelayService's
	// GetRelayUsage RPC.
	RelayServiceGetRelayUsageProcedure = "/admin.v1.RelayService/GetRelayUsage"
)

// RelayServiceClient is a client for the admin.v1.RelayService service.
type RelayServiceClient interface {
	CreateProvider(context.Context, *connect.Request[CreateProviderRequest]) (*connect.Response[relay.Provider], error)
	UpdateProvider(context.Context, *connect.Request[UpdateProviderRequest]) (*connect.Response[relay.Provider], error)
	DeleteProviders(context.Context, *connect.Request[DeleteProvidersRequest]) (*connect.Response[emptypb.Empty], error)
	GetProviderList(context.Context, *connect.Request[GetProviderListRequest]) (*connect.Response[GetProviderListResponse], error)
	GetProviderCodeList(context.Context, *connect.Request[GetProviderCodeListRequest]) (*connect.Response[GetProviderCodeListResponse], error)
	CreateModel(context.Context, *connect.Request[CreateModelRequest]) (*connect.Response[relay.Model], error)
	UpdateModel(context.Context, *connect.Request[UpdateModelRequest]) (*connect.Response[relay.Model], error)
	DeleteModels(context.Context, *connect.Request[DeleteModelsRequest]) (*connect.Response[emptypb.Empty], error)
	GetModelList(context.Context, *connect.Request[GetModelListRequest]) (*connect.Response[GetModelListResponse], error)
	CreateProviderApiKey(context.Context, *connect.Request[CreateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error)
	UpdateProviderApiKey(context.Context, *connect.Request[UpdateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error)
	DeleteProviderApiKeys(context.Context, *connect.Request[DeleteProviderApiKeysRequest]) (*connect.Response[emptypb.Empty], error)
	GetProviderApiKeyList(context.Context, *connect.Request[GetProviderApiKeyListRequest]) (*connect.Response[GetProviderApiKeyListResponse], error)
	CreateModelPricing(context.Context, *connect.Request[CreateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error)
	UpdateModelPricing(context.Context, *connect.Request[UpdateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error)
	DeleteModelPricings(context.Context, *connect.Request[DeleteModelPricingsRequest]) (*connect.Response[emptypb.Empty], error)
	GetModelPricingList(context.Context, *connect.Request[GetModelPricingListRequest]) (*connect.Response[GetModelPricingListResponse], error)
	CreateLedger(context.Context, *connect.Request[CreateLedgerRequest]) (*connect.Response[relay.Ledger], error)
	DeleteLedgers(context.Context, *connect.Request[DeleteLedgersRequest]) (*connect.Response[emptypb.Empty], error)
	GetLedgerList(context.Context, *connect.Request[GetLedgerListRequest]) (*connect.Response[GetLedgerListResponse], error)
	CreateAccountApiKey(context.Context, *connect.Request[CreateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error)
	UpdateAccountApiKey(context.Context, *connect.Request[UpdateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error)
	DeleteAccountApiKeys(context.Context, *connect.Request[DeleteAccountApiKeysRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountApiKeyList(context.Context, *connect.Request[GetAccountApiKeyListRequest]) (*connect.Response[GetAccountApiKeyListResponse], error)
	CreateAccount(context.Context, *connect.Request[CreateAccountRequest]) (*connect.Response[relay.Account], error)
	UpdateAccount(context.Context, *connect.Request[UpdateAccountRequest]) (*connect.Response[relay.Account], error)
	DeleteAccounts(context.Context, *connect.Request[DeleteAccountsRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountList(context.Context, *connect.Request[GetAccountListRequest]) (*connect.Response[GetAccountListResponse], error)
	GetRequestList(context.Context, *connect.Request[GetRequestListRequest]) (*connect.Response[GetRequestListResponse], error)
	DeleteRequests(context.Context, *connect.Request[DeleteRequestsRequest]) (*connect.Response[emptypb.Empty], error)
	GetRelayInfo(context.Context, *connect.Request[GetRelayInfoRequest]) (*connect.Response[GetRelayInfoResponse], error)
	GetTotalRelayUsage(context.Context, *connect.Request[GetTotalRelayUsageRequest]) (*connect.Response[GetTotalRelayUsageResponse], error)
	GetRelayUsage(context.Context, *connect.Request[GetRelayUsageRequest]) (*connect.Response[GetRelayUsageResponse], error)
}

// NewRelayServiceClient constructs a client for the admin.v1.RelayService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRelayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RelayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	relayServiceMethods := File_admin_v1_relay_proto.Services().ByName("RelayService").Methods()
	return &relayServiceClient{
		createProvider: connect.NewClient[CreateProviderRequest, relay.Provider](
			httpClient,
			baseURL+RelayServiceCreateProviderProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateProvider")),
			connect.WithClientOptions(opts...),
		),
		updateProvider: connect.NewClient[UpdateProviderRequest, relay.Provider](
			httpClient,
			baseURL+RelayServiceUpdateProviderProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteProviders: connect.NewClient[DeleteProvidersRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteProvidersProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteProviders")),
			connect.WithClientOptions(opts...),
		),
		getProviderList: connect.NewClient[GetProviderListRequest, GetProviderListResponse](
			httpClient,
			baseURL+RelayServiceGetProviderListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetProviderList")),
			connect.WithClientOptions(opts...),
		),
		getProviderCodeList: connect.NewClient[GetProviderCodeListRequest, GetProviderCodeListResponse](
			httpClient,
			baseURL+RelayServiceGetProviderCodeListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetProviderCodeList")),
			connect.WithClientOptions(opts...),
		),
		createModel: connect.NewClient[CreateModelRequest, relay.Model](
			httpClient,
			baseURL+RelayServiceCreateModelProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateModel")),
			connect.WithClientOptions(opts...),
		),
		updateModel: connect.NewClient[UpdateModelRequest, relay.Model](
			httpClient,
			baseURL+RelayServiceUpdateModelProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateModel")),
			connect.WithClientOptions(opts...),
		),
		deleteModels: connect.NewClient[DeleteModelsRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteModelsProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteModels")),
			connect.WithClientOptions(opts...),
		),
		getModelList: connect.NewClient[GetModelListRequest, GetModelListResponse](
			httpClient,
			baseURL+RelayServiceGetModelListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetModelList")),
			connect.WithClientOptions(opts...),
		),
		createProviderApiKey: connect.NewClient[CreateProviderApiKeyRequest, relay.ProviderApiKey](
			httpClient,
			baseURL+RelayServiceCreateProviderApiKeyProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateProviderApiKey")),
			connect.WithClientOptions(opts...),
		),
		updateProviderApiKey: connect.NewClient[UpdateProviderApiKeyRequest, relay.ProviderApiKey](
			httpClient,
			baseURL+RelayServiceUpdateProviderApiKeyProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateProviderApiKey")),
			connect.WithClientOptions(opts...),
		),
		deleteProviderApiKeys: connect.NewClient[DeleteProviderApiKeysRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteProviderApiKeysProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteProviderApiKeys")),
			connect.WithClientOptions(opts...),
		),
		getProviderApiKeyList: connect.NewClient[GetProviderApiKeyListRequest, GetProviderApiKeyListResponse](
			httpClient,
			baseURL+RelayServiceGetProviderApiKeyListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetProviderApiKeyList")),
			connect.WithClientOptions(opts...),
		),
		createModelPricing: connect.NewClient[CreateModelPricingRequest, relay.ModelPricing](
			httpClient,
			baseURL+RelayServiceCreateModelPricingProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateModelPricing")),
			connect.WithClientOptions(opts...),
		),
		updateModelPricing: connect.NewClient[UpdateModelPricingRequest, relay.ModelPricing](
			httpClient,
			baseURL+RelayServiceUpdateModelPricingProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateModelPricing")),
			connect.WithClientOptions(opts...),
		),
		deleteModelPricings: connect.NewClient[DeleteModelPricingsRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteModelPricingsProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteModelPricings")),
			connect.WithClientOptions(opts...),
		),
		getModelPricingList: connect.NewClient[GetModelPricingListRequest, GetModelPricingListResponse](
			httpClient,
			baseURL+RelayServiceGetModelPricingListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetModelPricingList")),
			connect.WithClientOptions(opts...),
		),
		createLedger: connect.NewClient[CreateLedgerRequest, relay.Ledger](
			httpClient,
			baseURL+RelayServiceCreateLedgerProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateLedger")),
			connect.WithClientOptions(opts...),
		),
		deleteLedgers: connect.NewClient[DeleteLedgersRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteLedgersProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteLedgers")),
			connect.WithClientOptions(opts...),
		),
		getLedgerList: connect.NewClient[GetLedgerListRequest, GetLedgerListResponse](
			httpClient,
			baseURL+RelayServiceGetLedgerListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetLedgerList")),
			connect.WithClientOptions(opts...),
		),
		createAccountApiKey: connect.NewClient[CreateAccountApiKeyRequest, relay.AccountApiKey](
			httpClient,
			baseURL+RelayServiceCreateAccountApiKeyProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateAccountApiKey")),
			connect.WithClientOptions(opts...),
		),
		updateAccountApiKey: connect.NewClient[UpdateAccountApiKeyRequest, relay.AccountApiKey](
			httpClient,
			baseURL+RelayServiceUpdateAccountApiKeyProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateAccountApiKey")),
			connect.WithClientOptions(opts...),
		),
		deleteAccountApiKeys: connect.NewClient[DeleteAccountApiKeysRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteAccountApiKeysProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteAccountApiKeys")),
			connect.WithClientOptions(opts...),
		),
		getAccountApiKeyList: connect.NewClient[GetAccountApiKeyListRequest, GetAccountApiKeyListResponse](
			httpClient,
			baseURL+RelayServiceGetAccountApiKeyListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetAccountApiKeyList")),
			connect.WithClientOptions(opts...),
		),
		createAccount: connect.NewClient[CreateAccountRequest, relay.Account](
			httpClient,
			baseURL+RelayServiceCreateAccountProcedure,
			connect.WithSchema(relayServiceMethods.ByName("CreateAccount")),
			connect.WithClientOptions(opts...),
		),
		updateAccount: connect.NewClient[UpdateAccountRequest, relay.Account](
			httpClient,
			baseURL+RelayServiceUpdateAccountProcedure,
			connect.WithSchema(relayServiceMethods.ByName("UpdateAccount")),
			connect.WithClientOptions(opts...),
		),
		deleteAccounts: connect.NewClient[DeleteAccountsRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteAccountsProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteAccounts")),
			connect.WithClientOptions(opts...),
		),
		getAccountList: connect.NewClient[GetAccountListRequest, GetAccountListResponse](
			httpClient,
			baseURL+RelayServiceGetAccountListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetAccountList")),
			connect.WithClientOptions(opts...),
		),
		getRequestList: connect.NewClient[GetRequestListRequest, GetRequestListResponse](
			httpClient,
			baseURL+RelayServiceGetRequestListProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetRequestList")),
			connect.WithClientOptions(opts...),
		),
		deleteRequests: connect.NewClient[DeleteRequestsRequest, emptypb.Empty](
			httpClient,
			baseURL+RelayServiceDeleteRequestsProcedure,
			connect.WithSchema(relayServiceMethods.ByName("DeleteRequests")),
			connect.WithClientOptions(opts...),
		),
		getRelayInfo: connect.NewClient[GetRelayInfoRequest, GetRelayInfoResponse](
			httpClient,
			baseURL+RelayServiceGetRelayInfoProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetRelayInfo")),
			connect.WithClientOptions(opts...),
		),
		getTotalRelayUsage: connect.NewClient[GetTotalRelayUsageRequest, GetTotalRelayUsageResponse](
			httpClient,
			baseURL+RelayServiceGetTotalRelayUsageProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetTotalRelayUsage")),
			connect.WithClientOptions(opts...),
		),
		getRelayUsage: connect.NewClient[GetRelayUsageRequest, GetRelayUsageResponse](
			httpClient,
			baseURL+RelayServiceGetRelayUsageProcedure,
			connect.WithSchema(relayServiceMethods.ByName("GetRelayUsage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// relayServiceClient implements RelayServiceClient.
type relayServiceClient struct {
	createProvider        *connect.Client[CreateProviderRequest, relay.Provider]
	updateProvider        *connect.Client[UpdateProviderRequest, relay.Provider]
	deleteProviders       *connect.Client[DeleteProvidersRequest, emptypb.Empty]
	getProviderList       *connect.Client[GetProviderListRequest, GetProviderListResponse]
	getProviderCodeList   *connect.Client[GetProviderCodeListRequest, GetProviderCodeListResponse]
	createModel           *connect.Client[CreateModelRequest, relay.Model]
	updateModel           *connect.Client[UpdateModelRequest, relay.Model]
	deleteModels          *connect.Client[DeleteModelsRequest, emptypb.Empty]
	getModelList          *connect.Client[GetModelListRequest, GetModelListResponse]
	createProviderApiKey  *connect.Client[CreateProviderApiKeyRequest, relay.ProviderApiKey]
	updateProviderApiKey  *connect.Client[UpdateProviderApiKeyRequest, relay.ProviderApiKey]
	deleteProviderApiKeys *connect.Client[DeleteProviderApiKeysRequest, emptypb.Empty]
	getProviderApiKeyList *connect.Client[GetProviderApiKeyListRequest, GetProviderApiKeyListResponse]
	createModelPricing    *connect.Client[CreateModelPricingRequest, relay.ModelPricing]
	updateModelPricing    *connect.Client[UpdateModelPricingRequest, relay.ModelPricing]
	deleteModelPricings   *connect.Client[DeleteModelPricingsRequest, emptypb.Empty]
	getModelPricingList   *connect.Client[GetModelPricingListRequest, GetModelPricingListResponse]
	createLedger          *connect.Client[CreateLedgerRequest, relay.Ledger]
	deleteLedgers         *connect.Client[DeleteLedgersRequest, emptypb.Empty]
	getLedgerList         *connect.Client[GetLedgerListRequest, GetLedgerListResponse]
	createAccountApiKey   *connect.Client[CreateAccountApiKeyRequest, relay.AccountApiKey]
	updateAccountApiKey   *connect.Client[UpdateAccountApiKeyRequest, relay.AccountApiKey]
	deleteAccountApiKeys  *connect.Client[DeleteAccountApiKeysRequest, emptypb.Empty]
	getAccountApiKeyList  *connect.Client[GetAccountApiKeyListRequest, GetAccountApiKeyListResponse]
	createAccount         *connect.Client[CreateAccountRequest, relay.Account]
	updateAccount         *connect.Client[UpdateAccountRequest, relay.Account]
	deleteAccounts        *connect.Client[DeleteAccountsRequest, emptypb.Empty]
	getAccountList        *connect.Client[GetAccountListRequest, GetAccountListResponse]
	getRequestList        *connect.Client[GetRequestListRequest, GetRequestListResponse]
	deleteRequests        *connect.Client[DeleteRequestsRequest, emptypb.Empty]
	getRelayInfo          *connect.Client[GetRelayInfoRequest, GetRelayInfoResponse]
	getTotalRelayUsage    *connect.Client[GetTotalRelayUsageRequest, GetTotalRelayUsageResponse]
	getRelayUsage         *connect.Client[GetRelayUsageRequest, GetRelayUsageResponse]
}

// CreateProvider calls admin.v1.RelayService.CreateProvider.
func (c *relayServiceClient) CreateProvider(ctx context.Context, req *connect.Request[CreateProviderRequest]) (*connect.Response[relay.Provider], error) {
	return c.createProvider.CallUnary(ctx, req)
}

// UpdateProvider calls admin.v1.RelayService.UpdateProvider.
func (c *relayServiceClient) UpdateProvider(ctx context.Context, req *connect.Request[UpdateProviderRequest]) (*connect.Response[relay.Provider], error) {
	return c.updateProvider.CallUnary(ctx, req)
}

// DeleteProviders calls admin.v1.RelayService.DeleteProviders.
func (c *relayServiceClient) DeleteProviders(ctx context.Context, req *connect.Request[DeleteProvidersRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteProviders.CallUnary(ctx, req)
}

// GetProviderList calls admin.v1.RelayService.GetProviderList.
func (c *relayServiceClient) GetProviderList(ctx context.Context, req *connect.Request[GetProviderListRequest]) (*connect.Response[GetProviderListResponse], error) {
	return c.getProviderList.CallUnary(ctx, req)
}

// GetProviderCodeList calls admin.v1.RelayService.GetProviderCodeList.
func (c *relayServiceClient) GetProviderCodeList(ctx context.Context, req *connect.Request[GetProviderCodeListRequest]) (*connect.Response[GetProviderCodeListResponse], error) {
	return c.getProviderCodeList.CallUnary(ctx, req)
}

// CreateModel calls admin.v1.RelayService.CreateModel.
func (c *relayServiceClient) CreateModel(ctx context.Context, req *connect.Request[CreateModelRequest]) (*connect.Response[relay.Model], error) {
	return c.createModel.CallUnary(ctx, req)
}

// UpdateModel calls admin.v1.RelayService.UpdateModel.
func (c *relayServiceClient) UpdateModel(ctx context.Context, req *connect.Request[UpdateModelRequest]) (*connect.Response[relay.Model], error) {
	return c.updateModel.CallUnary(ctx, req)
}

// DeleteModels calls admin.v1.RelayService.DeleteModels.
func (c *relayServiceClient) DeleteModels(ctx context.Context, req *connect.Request[DeleteModelsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteModels.CallUnary(ctx, req)
}

// GetModelList calls admin.v1.RelayService.GetModelList.
func (c *relayServiceClient) GetModelList(ctx context.Context, req *connect.Request[GetModelListRequest]) (*connect.Response[GetModelListResponse], error) {
	return c.getModelList.CallUnary(ctx, req)
}

// CreateProviderApiKey calls admin.v1.RelayService.CreateProviderApiKey.
func (c *relayServiceClient) CreateProviderApiKey(ctx context.Context, req *connect.Request[CreateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error) {
	return c.createProviderApiKey.CallUnary(ctx, req)
}

// UpdateProviderApiKey calls admin.v1.RelayService.UpdateProviderApiKey.
func (c *relayServiceClient) UpdateProviderApiKey(ctx context.Context, req *connect.Request[UpdateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error) {
	return c.updateProviderApiKey.CallUnary(ctx, req)
}

// DeleteProviderApiKeys calls admin.v1.RelayService.DeleteProviderApiKeys.
func (c *relayServiceClient) DeleteProviderApiKeys(ctx context.Context, req *connect.Request[DeleteProviderApiKeysRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteProviderApiKeys.CallUnary(ctx, req)
}

// GetProviderApiKeyList calls admin.v1.RelayService.GetProviderApiKeyList.
func (c *relayServiceClient) GetProviderApiKeyList(ctx context.Context, req *connect.Request[GetProviderApiKeyListRequest]) (*connect.Response[GetProviderApiKeyListResponse], error) {
	return c.getProviderApiKeyList.CallUnary(ctx, req)
}

// CreateModelPricing calls admin.v1.RelayService.CreateModelPricing.
func (c *relayServiceClient) CreateModelPricing(ctx context.Context, req *connect.Request[CreateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error) {
	return c.createModelPricing.CallUnary(ctx, req)
}

// UpdateModelPricing calls admin.v1.RelayService.UpdateModelPricing.
func (c *relayServiceClient) UpdateModelPricing(ctx context.Context, req *connect.Request[UpdateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error) {
	return c.updateModelPricing.CallUnary(ctx, req)
}

// DeleteModelPricings calls admin.v1.RelayService.DeleteModelPricings.
func (c *relayServiceClient) DeleteModelPricings(ctx context.Context, req *connect.Request[DeleteModelPricingsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteModelPricings.CallUnary(ctx, req)
}

// GetModelPricingList calls admin.v1.RelayService.GetModelPricingList.
func (c *relayServiceClient) GetModelPricingList(ctx context.Context, req *connect.Request[GetModelPricingListRequest]) (*connect.Response[GetModelPricingListResponse], error) {
	return c.getModelPricingList.CallUnary(ctx, req)
}

// CreateLedger calls admin.v1.RelayService.CreateLedger.
func (c *relayServiceClient) CreateLedger(ctx context.Context, req *connect.Request[CreateLedgerRequest]) (*connect.Response[relay.Ledger], error) {
	return c.createLedger.CallUnary(ctx, req)
}

// DeleteLedgers calls admin.v1.RelayService.DeleteLedgers.
func (c *relayServiceClient) DeleteLedgers(ctx context.Context, req *connect.Request[DeleteLedgersRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteLedgers.CallUnary(ctx, req)
}

// GetLedgerList calls admin.v1.RelayService.GetLedgerList.
func (c *relayServiceClient) GetLedgerList(ctx context.Context, req *connect.Request[GetLedgerListRequest]) (*connect.Response[GetLedgerListResponse], error) {
	return c.getLedgerList.CallUnary(ctx, req)
}

// CreateAccountApiKey calls admin.v1.RelayService.CreateAccountApiKey.
func (c *relayServiceClient) CreateAccountApiKey(ctx context.Context, req *connect.Request[CreateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error) {
	return c.createAccountApiKey.CallUnary(ctx, req)
}

// UpdateAccountApiKey calls admin.v1.RelayService.UpdateAccountApiKey.
func (c *relayServiceClient) UpdateAccountApiKey(ctx context.Context, req *connect.Request[UpdateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error) {
	return c.updateAccountApiKey.CallUnary(ctx, req)
}

// DeleteAccountApiKeys calls admin.v1.RelayService.DeleteAccountApiKeys.
func (c *relayServiceClient) DeleteAccountApiKeys(ctx context.Context, req *connect.Request[DeleteAccountApiKeysRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAccountApiKeys.CallUnary(ctx, req)
}

// GetAccountApiKeyList calls admin.v1.RelayService.GetAccountApiKeyList.
func (c *relayServiceClient) GetAccountApiKeyList(ctx context.Context, req *connect.Request[GetAccountApiKeyListRequest]) (*connect.Response[GetAccountApiKeyListResponse], error) {
	return c.getAccountApiKeyList.CallUnary(ctx, req)
}

// CreateAccount calls admin.v1.RelayService.CreateAccount.
func (c *relayServiceClient) CreateAccount(ctx context.Context, req *connect.Request[CreateAccountRequest]) (*connect.Response[relay.Account], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// UpdateAccount calls admin.v1.RelayService.UpdateAccount.
func (c *relayServiceClient) UpdateAccount(ctx context.Context, req *connect.Request[UpdateAccountRequest]) (*connect.Response[relay.Account], error) {
	return c.updateAccount.CallUnary(ctx, req)
}

// DeleteAccounts calls admin.v1.RelayService.DeleteAccounts.
func (c *relayServiceClient) DeleteAccounts(ctx context.Context, req *connect.Request[DeleteAccountsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAccounts.CallUnary(ctx, req)
}

// GetAccountList calls admin.v1.RelayService.GetAccountList.
func (c *relayServiceClient) GetAccountList(ctx context.Context, req *connect.Request[GetAccountListRequest]) (*connect.Response[GetAccountListResponse], error) {
	return c.getAccountList.CallUnary(ctx, req)
}

// GetRequestList calls admin.v1.RelayService.GetRequestList.
func (c *relayServiceClient) GetRequestList(ctx context.Context, req *connect.Request[GetRequestListRequest]) (*connect.Response[GetRequestListResponse], error) {
	return c.getRequestList.CallUnary(ctx, req)
}

// DeleteRequests calls admin.v1.RelayService.DeleteRequests.
func (c *relayServiceClient) DeleteRequests(ctx context.Context, req *connect.Request[DeleteRequestsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteRequests.CallUnary(ctx, req)
}

// GetRelayInfo calls admin.v1.RelayService.GetRelayInfo.
func (c *relayServiceClient) GetRelayInfo(ctx context.Context, req *connect.Request[GetRelayInfoRequest]) (*connect.Response[GetRelayInfoResponse], error) {
	return c.getRelayInfo.CallUnary(ctx, req)
}

// GetTotalRelayUsage calls admin.v1.RelayService.GetTotalRelayUsage.
func (c *relayServiceClient) GetTotalRelayUsage(ctx context.Context, req *connect.Request[GetTotalRelayUsageRequest]) (*connect.Response[GetTotalRelayUsageResponse], error) {
	return c.getTotalRelayUsage.CallUnary(ctx, req)
}

// GetRelayUsage calls admin.v1.RelayService.GetRelayUsage.
func (c *relayServiceClient) GetRelayUsage(ctx context.Context, req *connect.Request[GetRelayUsageRequest]) (*connect.Response[GetRelayUsageResponse], error) {
	return c.getRelayUsage.CallUnary(ctx, req)
}

// RelayServiceHandler is an implementation of the admin.v1.RelayService service.
type RelayServiceHandler interface {
	CreateProvider(context.Context, *connect.Request[CreateProviderRequest]) (*connect.Response[relay.Provider], error)
	UpdateProvider(context.Context, *connect.Request[UpdateProviderRequest]) (*connect.Response[relay.Provider], error)
	DeleteProviders(context.Context, *connect.Request[DeleteProvidersRequest]) (*connect.Response[emptypb.Empty], error)
	GetProviderList(context.Context, *connect.Request[GetProviderListRequest]) (*connect.Response[GetProviderListResponse], error)
	GetProviderCodeList(context.Context, *connect.Request[GetProviderCodeListRequest]) (*connect.Response[GetProviderCodeListResponse], error)
	CreateModel(context.Context, *connect.Request[CreateModelRequest]) (*connect.Response[relay.Model], error)
	UpdateModel(context.Context, *connect.Request[UpdateModelRequest]) (*connect.Response[relay.Model], error)
	DeleteModels(context.Context, *connect.Request[DeleteModelsRequest]) (*connect.Response[emptypb.Empty], error)
	GetModelList(context.Context, *connect.Request[GetModelListRequest]) (*connect.Response[GetModelListResponse], error)
	CreateProviderApiKey(context.Context, *connect.Request[CreateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error)
	UpdateProviderApiKey(context.Context, *connect.Request[UpdateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error)
	DeleteProviderApiKeys(context.Context, *connect.Request[DeleteProviderApiKeysRequest]) (*connect.Response[emptypb.Empty], error)
	GetProviderApiKeyList(context.Context, *connect.Request[GetProviderApiKeyListRequest]) (*connect.Response[GetProviderApiKeyListResponse], error)
	CreateModelPricing(context.Context, *connect.Request[CreateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error)
	UpdateModelPricing(context.Context, *connect.Request[UpdateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error)
	DeleteModelPricings(context.Context, *connect.Request[DeleteModelPricingsRequest]) (*connect.Response[emptypb.Empty], error)
	GetModelPricingList(context.Context, *connect.Request[GetModelPricingListRequest]) (*connect.Response[GetModelPricingListResponse], error)
	CreateLedger(context.Context, *connect.Request[CreateLedgerRequest]) (*connect.Response[relay.Ledger], error)
	DeleteLedgers(context.Context, *connect.Request[DeleteLedgersRequest]) (*connect.Response[emptypb.Empty], error)
	GetLedgerList(context.Context, *connect.Request[GetLedgerListRequest]) (*connect.Response[GetLedgerListResponse], error)
	CreateAccountApiKey(context.Context, *connect.Request[CreateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error)
	UpdateAccountApiKey(context.Context, *connect.Request[UpdateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error)
	DeleteAccountApiKeys(context.Context, *connect.Request[DeleteAccountApiKeysRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountApiKeyList(context.Context, *connect.Request[GetAccountApiKeyListRequest]) (*connect.Response[GetAccountApiKeyListResponse], error)
	CreateAccount(context.Context, *connect.Request[CreateAccountRequest]) (*connect.Response[relay.Account], error)
	UpdateAccount(context.Context, *connect.Request[UpdateAccountRequest]) (*connect.Response[relay.Account], error)
	DeleteAccounts(context.Context, *connect.Request[DeleteAccountsRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountList(context.Context, *connect.Request[GetAccountListRequest]) (*connect.Response[GetAccountListResponse], error)
	GetRequestList(context.Context, *connect.Request[GetRequestListRequest]) (*connect.Response[GetRequestListResponse], error)
	DeleteRequests(context.Context, *connect.Request[DeleteRequestsRequest]) (*connect.Response[emptypb.Empty], error)
	GetRelayInfo(context.Context, *connect.Request[GetRelayInfoRequest]) (*connect.Response[GetRelayInfoResponse], error)
	GetTotalRelayUsage(context.Context, *connect.Request[GetTotalRelayUsageRequest]) (*connect.Response[GetTotalRelayUsageResponse], error)
	GetRelayUsage(context.Context, *connect.Request[GetRelayUsageRequest]) (*connect.Response[GetRelayUsageResponse], error)
}

// NewRelayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRelayServiceHandler(svc RelayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	relayServiceMethods := File_admin_v1_relay_proto.Services().ByName("RelayService").Methods()
	relayServiceCreateProviderHandler := connect.NewUnaryHandler(
		RelayServiceCreateProviderProcedure,
		svc.CreateProvider,
		connect.WithSchema(relayServiceMethods.ByName("CreateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateProviderHandler := connect.NewUnaryHandler(
		RelayServiceUpdateProviderProcedure,
		svc.UpdateProvider,
		connect.WithSchema(relayServiceMethods.ByName("UpdateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteProvidersHandler := connect.NewUnaryHandler(
		RelayServiceDeleteProvidersProcedure,
		svc.DeleteProviders,
		connect.WithSchema(relayServiceMethods.ByName("DeleteProviders")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetProviderListHandler := connect.NewUnaryHandler(
		RelayServiceGetProviderListProcedure,
		svc.GetProviderList,
		connect.WithSchema(relayServiceMethods.ByName("GetProviderList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetProviderCodeListHandler := connect.NewUnaryHandler(
		RelayServiceGetProviderCodeListProcedure,
		svc.GetProviderCodeList,
		connect.WithSchema(relayServiceMethods.ByName("GetProviderCodeList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateModelHandler := connect.NewUnaryHandler(
		RelayServiceCreateModelProcedure,
		svc.CreateModel,
		connect.WithSchema(relayServiceMethods.ByName("CreateModel")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateModelHandler := connect.NewUnaryHandler(
		RelayServiceUpdateModelProcedure,
		svc.UpdateModel,
		connect.WithSchema(relayServiceMethods.ByName("UpdateModel")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteModelsHandler := connect.NewUnaryHandler(
		RelayServiceDeleteModelsProcedure,
		svc.DeleteModels,
		connect.WithSchema(relayServiceMethods.ByName("DeleteModels")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetModelListHandler := connect.NewUnaryHandler(
		RelayServiceGetModelListProcedure,
		svc.GetModelList,
		connect.WithSchema(relayServiceMethods.ByName("GetModelList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateProviderApiKeyHandler := connect.NewUnaryHandler(
		RelayServiceCreateProviderApiKeyProcedure,
		svc.CreateProviderApiKey,
		connect.WithSchema(relayServiceMethods.ByName("CreateProviderApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateProviderApiKeyHandler := connect.NewUnaryHandler(
		RelayServiceUpdateProviderApiKeyProcedure,
		svc.UpdateProviderApiKey,
		connect.WithSchema(relayServiceMethods.ByName("UpdateProviderApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteProviderApiKeysHandler := connect.NewUnaryHandler(
		RelayServiceDeleteProviderApiKeysProcedure,
		svc.DeleteProviderApiKeys,
		connect.WithSchema(relayServiceMethods.ByName("DeleteProviderApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetProviderApiKeyListHandler := connect.NewUnaryHandler(
		RelayServiceGetProviderApiKeyListProcedure,
		svc.GetProviderApiKeyList,
		connect.WithSchema(relayServiceMethods.ByName("GetProviderApiKeyList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateModelPricingHandler := connect.NewUnaryHandler(
		RelayServiceCreateModelPricingProcedure,
		svc.CreateModelPricing,
		connect.WithSchema(relayServiceMethods.ByName("CreateModelPricing")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateModelPricingHandler := connect.NewUnaryHandler(
		RelayServiceUpdateModelPricingProcedure,
		svc.UpdateModelPricing,
		connect.WithSchema(relayServiceMethods.ByName("UpdateModelPricing")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteModelPricingsHandler := connect.NewUnaryHandler(
		RelayServiceDeleteModelPricingsProcedure,
		svc.DeleteModelPricings,
		connect.WithSchema(relayServiceMethods.ByName("DeleteModelPricings")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetModelPricingListHandler := connect.NewUnaryHandler(
		RelayServiceGetModelPricingListProcedure,
		svc.GetModelPricingList,
		connect.WithSchema(relayServiceMethods.ByName("GetModelPricingList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateLedgerHandler := connect.NewUnaryHandler(
		RelayServiceCreateLedgerProcedure,
		svc.CreateLedger,
		connect.WithSchema(relayServiceMethods.ByName("CreateLedger")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteLedgersHandler := connect.NewUnaryHandler(
		RelayServiceDeleteLedgersProcedure,
		svc.DeleteLedgers,
		connect.WithSchema(relayServiceMethods.ByName("DeleteLedgers")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetLedgerListHandler := connect.NewUnaryHandler(
		RelayServiceGetLedgerListProcedure,
		svc.GetLedgerList,
		connect.WithSchema(relayServiceMethods.ByName("GetLedgerList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateAccountApiKeyHandler := connect.NewUnaryHandler(
		RelayServiceCreateAccountApiKeyProcedure,
		svc.CreateAccountApiKey,
		connect.WithSchema(relayServiceMethods.ByName("CreateAccountApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateAccountApiKeyHandler := connect.NewUnaryHandler(
		RelayServiceUpdateAccountApiKeyProcedure,
		svc.UpdateAccountApiKey,
		connect.WithSchema(relayServiceMethods.ByName("UpdateAccountApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteAccountApiKeysHandler := connect.NewUnaryHandler(
		RelayServiceDeleteAccountApiKeysProcedure,
		svc.DeleteAccountApiKeys,
		connect.WithSchema(relayServiceMethods.ByName("DeleteAccountApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetAccountApiKeyListHandler := connect.NewUnaryHandler(
		RelayServiceGetAccountApiKeyListProcedure,
		svc.GetAccountApiKeyList,
		connect.WithSchema(relayServiceMethods.ByName("GetAccountApiKeyList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceCreateAccountHandler := connect.NewUnaryHandler(
		RelayServiceCreateAccountProcedure,
		svc.CreateAccount,
		connect.WithSchema(relayServiceMethods.ByName("CreateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceUpdateAccountHandler := connect.NewUnaryHandler(
		RelayServiceUpdateAccountProcedure,
		svc.UpdateAccount,
		connect.WithSchema(relayServiceMethods.ByName("UpdateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteAccountsHandler := connect.NewUnaryHandler(
		RelayServiceDeleteAccountsProcedure,
		svc.DeleteAccounts,
		connect.WithSchema(relayServiceMethods.ByName("DeleteAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetAccountListHandler := connect.NewUnaryHandler(
		RelayServiceGetAccountListProcedure,
		svc.GetAccountList,
		connect.WithSchema(relayServiceMethods.ByName("GetAccountList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetRequestListHandler := connect.NewUnaryHandler(
		RelayServiceGetRequestListProcedure,
		svc.GetRequestList,
		connect.WithSchema(relayServiceMethods.ByName("GetRequestList")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceDeleteRequestsHandler := connect.NewUnaryHandler(
		RelayServiceDeleteRequestsProcedure,
		svc.DeleteRequests,
		connect.WithSchema(relayServiceMethods.ByName("DeleteRequests")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetRelayInfoHandler := connect.NewUnaryHandler(
		RelayServiceGetRelayInfoProcedure,
		svc.GetRelayInfo,
		connect.WithSchema(relayServiceMethods.ByName("GetRelayInfo")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetTotalRelayUsageHandler := connect.NewUnaryHandler(
		RelayServiceGetTotalRelayUsageProcedure,
		svc.GetTotalRelayUsage,
		connect.WithSchema(relayServiceMethods.ByName("GetTotalRelayUsage")),
		connect.WithHandlerOptions(opts...),
	)
	relayServiceGetRelayUsageHandler := connect.NewUnaryHandler(
		RelayServiceGetRelayUsageProcedure,
		svc.GetRelayUsage,
		connect.WithSchema(relayServiceMethods.ByName("GetRelayUsage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admin.v1.RelayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RelayServiceCreateProviderProcedure:
			relayServiceCreateProviderHandler.ServeHTTP(w, r)
		case RelayServiceUpdateProviderProcedure:
			relayServiceUpdateProviderHandler.ServeHTTP(w, r)
		case RelayServiceDeleteProvidersProcedure:
			relayServiceDeleteProvidersHandler.ServeHTTP(w, r)
		case RelayServiceGetProviderListProcedure:
			relayServiceGetProviderListHandler.ServeHTTP(w, r)
		case RelayServiceGetProviderCodeListProcedure:
			relayServiceGetProviderCodeListHandler.ServeHTTP(w, r)
		case RelayServiceCreateModelProcedure:
			relayServiceCreateModelHandler.ServeHTTP(w, r)
		case RelayServiceUpdateModelProcedure:
			relayServiceUpdateModelHandler.ServeHTTP(w, r)
		case RelayServiceDeleteModelsProcedure:
			relayServiceDeleteModelsHandler.ServeHTTP(w, r)
		case RelayServiceGetModelListProcedure:
			relayServiceGetModelListHandler.ServeHTTP(w, r)
		case RelayServiceCreateProviderApiKeyProcedure:
			relayServiceCreateProviderApiKeyHandler.ServeHTTP(w, r)
		case RelayServiceUpdateProviderApiKeyProcedure:
			relayServiceUpdateProviderApiKeyHandler.ServeHTTP(w, r)
		case RelayServiceDeleteProviderApiKeysProcedure:
			relayServiceDeleteProviderApiKeysHandler.ServeHTTP(w, r)
		case RelayServiceGetProviderApiKeyListProcedure:
			relayServiceGetProviderApiKeyListHandler.ServeHTTP(w, r)
		case RelayServiceCreateModelPricingProcedure:
			relayServiceCreateModelPricingHandler.ServeHTTP(w, r)
		case RelayServiceUpdateModelPricingProcedure:
			relayServiceUpdateModelPricingHandler.ServeHTTP(w, r)
		case RelayServiceDeleteModelPricingsProcedure:
			relayServiceDeleteModelPricingsHandler.ServeHTTP(w, r)
		case RelayServiceGetModelPricingListProcedure:
			relayServiceGetModelPricingListHandler.ServeHTTP(w, r)
		case RelayServiceCreateLedgerProcedure:
			relayServiceCreateLedgerHandler.ServeHTTP(w, r)
		case RelayServiceDeleteLedgersProcedure:
			relayServiceDeleteLedgersHandler.ServeHTTP(w, r)
		case RelayServiceGetLedgerListProcedure:
			relayServiceGetLedgerListHandler.ServeHTTP(w, r)
		case RelayServiceCreateAccountApiKeyProcedure:
			relayServiceCreateAccountApiKeyHandler.ServeHTTP(w, r)
		case RelayServiceUpdateAccountApiKeyProcedure:
			relayServiceUpdateAccountApiKeyHandler.ServeHTTP(w, r)
		case RelayServiceDeleteAccountApiKeysProcedure:
			relayServiceDeleteAccountApiKeysHandler.ServeHTTP(w, r)
		case RelayServiceGetAccountApiKeyListProcedure:
			relayServiceGetAccountApiKeyListHandler.ServeHTTP(w, r)
		case RelayServiceCreateAccountProcedure:
			relayServiceCreateAccountHandler.ServeHTTP(w, r)
		case RelayServiceUpdateAccountProcedure:
			relayServiceUpdateAccountHandler.ServeHTTP(w, r)
		case RelayServiceDeleteAccountsProcedure:
			relayServiceDeleteAccountsHandler.ServeHTTP(w, r)
		case RelayServiceGetAccountListProcedure:
			relayServiceGetAccountListHandler.ServeHTTP(w, r)
		case RelayServiceGetRequestListProcedure:
			relayServiceGetRequestListHandler.ServeHTTP(w, r)
		case RelayServiceDeleteRequestsProcedure:
			relayServiceDeleteRequestsHandler.ServeHTTP(w, r)
		case RelayServiceGetRelayInfoProcedure:
			relayServiceGetRelayInfoHandler.ServeHTTP(w, r)
		case RelayServiceGetTotalRelayUsageProcedure:
			relayServiceGetTotalRelayUsageHandler.ServeHTTP(w, r)
		case RelayServiceGetRelayUsageProcedure:
			relayServiceGetRelayUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRelayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRelayServiceHandler struct{}

func (UnimplementedRelayServiceHandler) CreateProvider(context.Context, *connect.Request[CreateProviderRequest]) (*connect.Response[relay.Provider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateProvider is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateProvider(context.Context, *connect.Request[UpdateProviderRequest]) (*connect.Response[relay.Provider], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateProvider is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteProviders(context.Context, *connect.Request[DeleteProvidersRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteProviders is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetProviderList(context.Context, *connect.Request[GetProviderListRequest]) (*connect.Response[GetProviderListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetProviderList is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetProviderCodeList(context.Context, *connect.Request[GetProviderCodeListRequest]) (*connect.Response[GetProviderCodeListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetProviderCodeList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateModel(context.Context, *connect.Request[CreateModelRequest]) (*connect.Response[relay.Model], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateModel is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateModel(context.Context, *connect.Request[UpdateModelRequest]) (*connect.Response[relay.Model], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateModel is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteModels(context.Context, *connect.Request[DeleteModelsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteModels is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetModelList(context.Context, *connect.Request[GetModelListRequest]) (*connect.Response[GetModelListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetModelList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateProviderApiKey(context.Context, *connect.Request[CreateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateProviderApiKey is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateProviderApiKey(context.Context, *connect.Request[UpdateProviderApiKeyRequest]) (*connect.Response[relay.ProviderApiKey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateProviderApiKey is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteProviderApiKeys(context.Context, *connect.Request[DeleteProviderApiKeysRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteProviderApiKeys is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetProviderApiKeyList(context.Context, *connect.Request[GetProviderApiKeyListRequest]) (*connect.Response[GetProviderApiKeyListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetProviderApiKeyList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateModelPricing(context.Context, *connect.Request[CreateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateModelPricing is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateModelPricing(context.Context, *connect.Request[UpdateModelPricingRequest]) (*connect.Response[relay.ModelPricing], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateModelPricing is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteModelPricings(context.Context, *connect.Request[DeleteModelPricingsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteModelPricings is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetModelPricingList(context.Context, *connect.Request[GetModelPricingListRequest]) (*connect.Response[GetModelPricingListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetModelPricingList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateLedger(context.Context, *connect.Request[CreateLedgerRequest]) (*connect.Response[relay.Ledger], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateLedger is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteLedgers(context.Context, *connect.Request[DeleteLedgersRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteLedgers is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetLedgerList(context.Context, *connect.Request[GetLedgerListRequest]) (*connect.Response[GetLedgerListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetLedgerList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateAccountApiKey(context.Context, *connect.Request[CreateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateAccountApiKey is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateAccountApiKey(context.Context, *connect.Request[UpdateAccountApiKeyRequest]) (*connect.Response[relay.AccountApiKey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateAccountApiKey is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteAccountApiKeys(context.Context, *connect.Request[DeleteAccountApiKeysRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteAccountApiKeys is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetAccountApiKeyList(context.Context, *connect.Request[GetAccountApiKeyListRequest]) (*connect.Response[GetAccountApiKeyListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetAccountApiKeyList is not implemented"))
}

func (UnimplementedRelayServiceHandler) CreateAccount(context.Context, *connect.Request[CreateAccountRequest]) (*connect.Response[relay.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.CreateAccount is not implemented"))
}

func (UnimplementedRelayServiceHandler) UpdateAccount(context.Context, *connect.Request[UpdateAccountRequest]) (*connect.Response[relay.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.UpdateAccount is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteAccounts(context.Context, *connect.Request[DeleteAccountsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteAccounts is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetAccountList(context.Context, *connect.Request[GetAccountListRequest]) (*connect.Response[GetAccountListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetAccountList is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetRequestList(context.Context, *connect.Request[GetRequestListRequest]) (*connect.Response[GetRequestListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetRequestList is not implemented"))
}

func (UnimplementedRelayServiceHandler) DeleteRequests(context.Context, *connect.Request[DeleteRequestsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.DeleteRequests is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetRelayInfo(context.Context, *connect.Request[GetRelayInfoRequest]) (*connect.Response[GetRelayInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetRelayInfo is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetTotalRelayUsage(context.Context, *connect.Request[GetTotalRelayUsageRequest]) (*connect.Response[GetTotalRelayUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetTotalRelayUsage is not implemented"))
}

func (UnimplementedRelayServiceHandler) GetRelayUsage(context.Context, *connect.Request[GetRelayUsageRequest]) (*connect.Response[GetRelayUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.RelayService.GetRelayUsage is not implemented"))
}
