// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: admin/v1/system.proto

package v1

import (
	system "github.com/modelgate/modelgate/pkg/proto/model/system"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *system.Permission     `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePermissionRequest) GetPermission() *system.Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *system.Permission     `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePermissionRequest) GetPermission() *system.Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *UpdatePermissionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeletePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionsRequest) Reset() {
	*x = DeletePermissionsRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionsRequest) ProtoMessage() {}

func (x *DeletePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionsRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePermissionsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetPermissionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionListRequest) Reset() {
	*x = GetPermissionListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionListRequest) ProtoMessage() {}

func (x *GetPermissionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionListRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionListRequest) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetPermissionListRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetPermissionListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetPermissionListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPermissionListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetPermissionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*system.Permission   `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionListResponse) Reset() {
	*x = GetPermissionListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionListResponse) ProtoMessage() {}

func (x *GetPermissionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionListResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermissionListResponse) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetPermissionListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetPermissionListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPermissionListResponse) GetRecords() []*system.Permission {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetApiListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiListRequest) Reset() {
	*x = GetApiListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiListRequest) ProtoMessage() {}

func (x *GetApiListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiListRequest.ProtoReflect.Descriptor instead.
func (*GetApiListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{5}
}

type GetApiListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []string               `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiListResponse) Reset() {
	*x = GetApiListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiListResponse) ProtoMessage() {}

func (x *GetApiListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiListResponse.ProtoReflect.Descriptor instead.
func (*GetApiListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *GetApiListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetApiListResponse) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetButtonListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetButtonListRequest) Reset() {
	*x = GetButtonListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetButtonListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButtonListRequest) ProtoMessage() {}

func (x *GetButtonListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButtonListRequest.ProtoReflect.Descriptor instead.
func (*GetButtonListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{7}
}

type GetButtonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*system.ButtonNode   `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetButtonListResponse) Reset() {
	*x = GetButtonListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetButtonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButtonListResponse) ProtoMessage() {}

func (x *GetButtonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButtonListResponse.ProtoReflect.Descriptor instead.
func (*GetButtonListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *GetButtonListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetButtonListResponse) GetRecords() []*system.ButtonNode {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpdateRolePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Home          string                 `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	MenuIds       []int64                `protobuf:"varint,3,rep,packed,name=menu_ids,json=menuIds,proto3" json:"menu_ids,omitempty"`
	Buttons       []string               `protobuf:"bytes,4,rep,name=buttons,proto3" json:"buttons,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolePermissionRequest) Reset() {
	*x = UpdateRolePermissionRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolePermissionRequest) ProtoMessage() {}

func (x *UpdateRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRolePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRolePermissionRequest) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *UpdateRolePermissionRequest) GetMenuIds() []int64 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *UpdateRolePermissionRequest) GetButtons() []string {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *UpdateRolePermissionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type GetRoleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleInfoRequest) Reset() {
	*x = GetRoleInfoRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleInfoRequest) ProtoMessage() {}

func (x *GetRoleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoleInfoRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoleInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMenuTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuTreeRequest) Reset() {
	*x = GetMenuTreeRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeRequest) ProtoMessage() {}

func (x *GetMenuTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeRequest.ProtoReflect.Descriptor instead.
func (*GetMenuTreeRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{11}
}

type GetMenuTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*system.MenuNode     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuTreeResponse) Reset() {
	*x = GetMenuTreeResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeResponse) ProtoMessage() {}

func (x *GetMenuTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeResponse.ProtoReflect.Descriptor instead.
func (*GetMenuTreeResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{12}
}

func (x *GetMenuTreeResponse) GetRecords() []*system.MenuNode {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetPageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageListRequest) Reset() {
	*x = GetPageListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageListRequest) ProtoMessage() {}

func (x *GetPageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageListRequest.ProtoReflect.Descriptor instead.
func (*GetPageListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{13}
}

func (x *GetPageListRequest) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetPageListRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetPageListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GetPageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []string               `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageListResponse) Reset() {
	*x = GetPageListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageListResponse) ProtoMessage() {}

func (x *GetPageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageListResponse.ProtoReflect.Descriptor instead.
func (*GetPageListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{14}
}

func (x *GetPageListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPageListResponse) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{15}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildTime     string                 `protobuf:"bytes,2,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	GitCommit     string                 `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{16}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

type GetUserRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoutesRequest) Reset() {
	*x = GetUserRoutesRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoutesRequest) ProtoMessage() {}

func (x *GetUserRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoutesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{17}
}

type GetUserRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*system.MenuRoute    `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Home          string                 `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoutesResponse) Reset() {
	*x = GetUserRoutesResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoutesResponse) ProtoMessage() {}

func (x *GetUserRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoutesResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserRoutesResponse) GetRoutes() []*system.MenuRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetUserRoutesResponse) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

type GetConstantRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConstantRoutesRequest) Reset() {
	*x = GetConstantRoutesRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstantRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstantRoutesRequest) ProtoMessage() {}

func (x *GetConstantRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstantRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetConstantRoutesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{19}
}

type GetConstantRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*system.MenuRoute    `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConstantRoutesResponse) Reset() {
	*x = GetConstantRoutesResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConstantRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConstantRoutesResponse) ProtoMessage() {}

func (x *GetConstantRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConstantRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetConstantRoutesResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{20}
}

func (x *GetConstantRoutesResponse) GetRoutes() []*system.MenuRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *system.Menu           `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{21}
}

func (x *CreateMenuRequest) GetMenu() *system.Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type UpdateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *system.Menu           `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateMenuRequest) GetMenu() *system.Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *UpdateMenuRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenusRequest) Reset() {
	*x = DeleteMenusRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenusRequest) ProtoMessage() {}

func (x *DeleteMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenusRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenusRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteMenusRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMenuListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	RouteName     string                 `protobuf:"bytes,5,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	RoutePath     string                 `protobuf:"bytes,6,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	Component     string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`
	I18NKey       string                 `protobuf:"bytes,8,opt,name=i18n_key,json=i18nKey,proto3" json:"i18n_key,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuListRequest) Reset() {
	*x = GetMenuListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuListRequest) ProtoMessage() {}

func (x *GetMenuListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuListRequest.ProtoReflect.Descriptor instead.
func (*GetMenuListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{24}
}

func (x *GetMenuListRequest) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetMenuListRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetMenuListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetMenuListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMenuListRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetMenuListRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *GetMenuListRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *GetMenuListRequest) GetI18NKey() string {
	if x != nil {
		return x.I18NKey
	}
	return ""
}

func (x *GetMenuListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMenuListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*system.Menu         `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuListResponse) Reset() {
	*x = GetMenuListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuListResponse) ProtoMessage() {}

func (x *GetMenuListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuListResponse.ProtoReflect.Descriptor instead.
func (*GetMenuListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{25}
}

func (x *GetMenuListResponse) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetMenuListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetMenuListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMenuListResponse) GetRecords() []*system.Menu {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListRequest) Reset() {
	*x = GetUserListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRequest) ProtoMessage() {}

func (x *GetUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserListRequest) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetUserListRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetUserListRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserListRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserListRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserListRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserListRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*system.User         `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResponse) Reset() {
	*x = GetUserListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResponse) ProtoMessage() {}

func (x *GetUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResponse.ProtoReflect.Descriptor instead.
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserListResponse) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetUserListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserListResponse) GetRecords() []*system.User {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *system.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{28}
}

func (x *CreateUserRequest) GetUser() *system.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *system.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateUserRequest) GetUser() *system.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersRequest) Reset() {
	*x = DeleteUsersRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersRequest) ProtoMessage() {}

func (x *DeleteUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteUsersRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetRoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListRequest) Reset() {
	*x = GetRoleListRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListRequest) ProtoMessage() {}

func (x *GetRoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListRequest.ProtoReflect.Descriptor instead.
func (*GetRoleListRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{31}
}

func (x *GetRoleListRequest) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetRoleListRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetRoleListRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetRoleListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoleListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetRoleListRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRoleListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*system.Role         `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListResponse) Reset() {
	*x = GetRoleListResponse{}
	mi := &file_admin_v1_system_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListResponse) ProtoMessage() {}

func (x *GetRoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListResponse.ProtoReflect.Descriptor instead.
func (*GetRoleListResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{32}
}

func (x *GetRoleListResponse) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetRoleListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetRoleListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRoleListResponse) GetRecords() []*system.Role {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *system.Role           `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{33}
}

func (x *CreateRoleRequest) GetRole() *system.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *system.Role           `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateRoleRequest) GetRole() *system.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRolesRequest) Reset() {
	*x = DeleteRolesRequest{}
	mi := &file_admin_v1_system_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRolesRequest) ProtoMessage() {}

func (x *DeleteRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_system_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRolesRequest.ProtoReflect.Descriptor instead.
func (*DeleteRolesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_system_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteRolesRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_admin_v1_system_proto protoreflect.FileDescriptor

const file_admin_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x15admin/v1/system.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x17model/system/user.proto\x1a\x17model/system/role.proto\x1a\x17model/system/menu.proto\x1a\x1dmodel/system/permission.proto\"M\n" +
	"\x17CreatePermissionRequest\x122\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x12.system.PermissionR\n" +
	"permission\"\x8a\x01\n" +
	"\x17UpdatePermissionRequest\x122\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x12.system.PermissionR\n" +
	"permission\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\",\n" +
	"\x18DeletePermissionsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\x8b\x01\n" +
	"\x18GetPermissionListRequest\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\"\x8d\x01\n" +
	"\x19GetPermissionListResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12,\n" +
	"\arecords\x18\x04 \x03(\v2\x12.system.PermissionR\arecords\"\x13\n" +
	"\x11GetApiListRequest\"D\n" +
	"\x12GetApiListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\arecords\x18\x02 \x03(\tR\arecords\"\x16\n" +
	"\x14GetButtonListRequest\"[\n" +
	"\x15GetButtonListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12,\n" +
	"\arecords\x18\x02 \x03(\v2\x12.system.ButtonNodeR\arecords\"\xb3\x01\n" +
	"\x1bUpdateRolePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04home\x18\x02 \x01(\tR\x04home\x12\x19\n" +
	"\bmenu_ids\x18\x03 \x03(\x03R\amenuIds\x12\x18\n" +
	"\abuttons\x18\x04 \x03(\tR\abuttons\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"$\n" +
	"\x12GetRoleInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12GetMenuTreeRequest\"A\n" +
	"\x13GetMenuTreeResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.system.MenuNodeR\arecords\"]\n" +
	"\x12GetPageListRequest\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"E\n" +
	"\x13GetPageListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\arecords\x18\x02 \x03(\tR\arecords\"\x13\n" +
	"\x11GetVersionRequest\"l\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_time\x18\x02 \x01(\tR\tbuildTime\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x03 \x01(\tR\tgitCommit\"\x16\n" +
	"\x14GetUserRoutesRequest\"V\n" +
	"\x15GetUserRoutesResponse\x12)\n" +
	"\x06routes\x18\x01 \x03(\v2\x11.system.MenuRouteR\x06routes\x12\x12\n" +
	"\x04home\x18\x02 \x01(\tR\x04home\"\x1a\n" +
	"\x18GetConstantRoutesRequest\"F\n" +
	"\x19GetConstantRoutesResponse\x12)\n" +
	"\x06routes\x18\x01 \x03(\v2\x11.system.MenuRouteR\x06routes\"5\n" +
	"\x11CreateMenuRequest\x12 \n" +
	"\x04menu\x18\x01 \x01(\v2\f.system.MenuR\x04menu\"r\n" +
	"\x11UpdateMenuRequest\x12 \n" +
	"\x04menu\x18\x01 \x01(\v2\f.system.MenuR\x04menu\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"&\n" +
	"\x12DeleteMenusRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\x80\x02\n" +
	"\x12GetMenuListRequest\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"route_name\x18\x05 \x01(\tR\trouteName\x12\x1d\n" +
	"\n" +
	"route_path\x18\x06 \x01(\tR\troutePath\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x19\n" +
	"\bi18n_key\x18\b \x01(\tR\ai18nKey\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\x81\x01\n" +
	"\x13GetMenuListResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12&\n" +
	"\arecords\x18\x04 \x03(\v2\f.system.MenuR\arecords\"\xf1\x01\n" +
	"\x12GetUserListRequest\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\x81\x01\n" +
	"\x13GetUserListResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12&\n" +
	"\arecords\x18\x04 \x03(\v2\f.system.UserR\arecords\"5\n" +
	"\x11CreateUserRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.system.UserR\x04user\"r\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.system.UserR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"&\n" +
	"\x12DeleteUsersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\xbf\x01\n" +
	"\x12GetRoleListRequest\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x81\x01\n" +
	"\x13GetRoleListResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12&\n" +
	"\arecords\x18\x04 \x03(\v2\f.system.RoleR\arecords\"5\n" +
	"\x11CreateRoleRequest\x12 \n" +
	"\x04role\x18\x01 \x01(\v2\f.system.RoleR\x04role\"r\n" +
	"\x11UpdateRoleRequest\x12 \n" +
	"\x04role\x18\x01 \x01(\v2\f.system.RoleR\x04role\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"&\n" +
	"\x12DeleteRolesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids2\xc3\x0e\n" +
	"\rSystemService\x12L\n" +
	"\vGetUserList\x12\x1c.admin.v1.GetUserListRequest\x1a\x1d.admin.v1.GetUserListResponse\"\x00\x129\n" +
	"\n" +
	"CreateUser\x12\x1b.admin.v1.CreateUserRequest\x1a\f.system.User\"\x00\x129\n" +
	"\n" +
	"UpdateUser\x12\x1b.admin.v1.UpdateUserRequest\x1a\f.system.User\"\x00\x12E\n" +
	"\vDeleteUsers\x12\x1c.admin.v1.DeleteUsersRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\vGetRoleList\x12\x1c.admin.v1.GetRoleListRequest\x1a\x1d.admin.v1.GetRoleListResponse\"\x00\x129\n" +
	"\n" +
	"CreateRole\x12\x1b.admin.v1.CreateRoleRequest\x1a\f.system.Role\"\x00\x129\n" +
	"\n" +
	"UpdateRole\x12\x1b.admin.v1.UpdateRoleRequest\x1a\f.system.Role\"\x00\x12M\n" +
	"\x14UpdateRolePermission\x12%.admin.v1.UpdateRolePermissionRequest\x1a\f.system.Role\"\x00\x12E\n" +
	"\vDeleteRoles\x12\x1c.admin.v1.DeleteRolesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\vGetRoleInfo\x12\x1c.admin.v1.GetRoleInfoRequest\x1a\f.system.Role\"\x00\x129\n" +
	"\n" +
	"CreateMenu\x12\x1b.admin.v1.CreateMenuRequest\x1a\f.system.Menu\"\x00\x129\n" +
	"\n" +
	"UpdateMenu\x12\x1b.admin.v1.UpdateMenuRequest\x1a\f.system.Menu\"\x00\x12E\n" +
	"\vDeleteMenus\x12\x1c.admin.v1.DeleteMenusRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\vGetMenuList\x12\x1c.admin.v1.GetMenuListRequest\x1a\x1d.admin.v1.GetMenuListResponse\"\x00\x12L\n" +
	"\vGetPageList\x12\x1c.admin.v1.GetPageListRequest\x1a\x1d.admin.v1.GetPageListResponse\"\x00\x12R\n" +
	"\rGetButtonList\x12\x1e.admin.v1.GetButtonListRequest\x1a\x1f.admin.v1.GetButtonListResponse\"\x00\x12L\n" +
	"\vGetMenuTree\x12\x1c.admin.v1.GetMenuTreeRequest\x1a\x1d.admin.v1.GetMenuTreeResponse\"\x00\x12^\n" +
	"\x11GetConstantRoutes\x12\".admin.v1.GetConstantRoutesRequest\x1a#.admin.v1.GetConstantRoutesResponse\"\x00\x12R\n" +
	"\rGetUserRoutes\x12\x1e.admin.v1.GetUserRoutesRequest\x1a\x1f.admin.v1.GetUserRoutesResponse\"\x00\x12I\n" +
	"\n" +
	"GetApiList\x12\x1b.admin.v1.GetApiListRequest\x1a\x1c.admin.v1.GetApiListResponse\"\x00\x12K\n" +
	"\x10CreatePermission\x12!.admin.v1.CreatePermissionRequest\x1a\x12.system.Permission\"\x00\x12K\n" +
	"\x10UpdatePermission\x12!.admin.v1.UpdatePermissionRequest\x1a\x12.system.Permission\"\x00\x12Q\n" +
	"\x11DeletePermissions\x12\".admin.v1.DeletePermissionsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12^\n" +
	"\x11GetPermissionList\x12\".admin.v1.GetPermissionListRequest\x1a#.admin.v1.GetPermissionListResponse\"\x00\x12I\n" +
	"\n" +
	"GetVersion\x12\x1b.admin.v1.GetVersionRequest\x1a\x1c.admin.v1.GetVersionResponse\"\x00B3Z1github.com/modelgate/modelgate/pkg/proto/admin/v1b\x06proto3"

var (
	file_admin_v1_system_proto_rawDescOnce sync.Once
	file_admin_v1_system_proto_rawDescData []byte
)

func file_admin_v1_system_proto_rawDescGZIP() []byte {
	file_admin_v1_system_proto_rawDescOnce.Do(func() {
		file_admin_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_system_proto_rawDesc), len(file_admin_v1_system_proto_rawDesc)))
	})
	return file_admin_v1_system_proto_rawDescData
}

var file_admin_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_admin_v1_system_proto_goTypes = []any{
	(*CreatePermissionRequest)(nil),     // 0: admin.v1.CreatePermissionRequest
	(*UpdatePermissionRequest)(nil),     // 1: admin.v1.UpdatePermissionRequest
	(*DeletePermissionsRequest)(nil),    // 2: admin.v1.DeletePermissionsRequest
	(*GetPermissionListRequest)(nil),    // 3: admin.v1.GetPermissionListRequest
	(*GetPermissionListResponse)(nil),   // 4: admin.v1.GetPermissionListResponse
	(*GetApiListRequest)(nil),           // 5: admin.v1.GetApiListRequest
	(*GetApiListResponse)(nil),          // 6: admin.v1.GetApiListResponse
	(*GetButtonListRequest)(nil),        // 7: admin.v1.GetButtonListRequest
	(*GetButtonListResponse)(nil),       // 8: admin.v1.GetButtonListResponse
	(*UpdateRolePermissionRequest)(nil), // 9: admin.v1.UpdateRolePermissionRequest
	(*GetRoleInfoRequest)(nil),          // 10: admin.v1.GetRoleInfoRequest
	(*GetMenuTreeRequest)(nil),          // 11: admin.v1.GetMenuTreeRequest
	(*GetMenuTreeResponse)(nil),         // 12: admin.v1.GetMenuTreeResponse
	(*GetPageListRequest)(nil),          // 13: admin.v1.GetPageListRequest
	(*GetPageListResponse)(nil),         // 14: admin.v1.GetPageListResponse
	(*GetVersionRequest)(nil),           // 15: admin.v1.GetVersionRequest
	(*GetVersionResponse)(nil),          // 16: admin.v1.GetVersionResponse
	(*GetUserRoutesRequest)(nil),        // 17: admin.v1.GetUserRoutesRequest
	(*GetUserRoutesResponse)(nil),       // 18: admin.v1.GetUserRoutesResponse
	(*GetConstantRoutesRequest)(nil),    // 19: admin.v1.GetConstantRoutesRequest
	(*GetConstantRoutesResponse)(nil),   // 20: admin.v1.GetConstantRoutesResponse
	(*CreateMenuRequest)(nil),           // 21: admin.v1.CreateMenuRequest
	(*UpdateMenuRequest)(nil),           // 22: admin.v1.UpdateMenuRequest
	(*DeleteMenusRequest)(nil),          // 23: admin.v1.DeleteMenusRequest
	(*GetMenuListRequest)(nil),          // 24: admin.v1.GetMenuListRequest
	(*GetMenuListResponse)(nil),         // 25: admin.v1.GetMenuListResponse
	(*GetUserListRequest)(nil),          // 26: admin.v1.GetUserListRequest
	(*GetUserListResponse)(nil),         // 27: admin.v1.GetUserListResponse
	(*CreateUserRequest)(nil),           // 28: admin.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),           // 29: admin.v1.UpdateUserRequest
	(*DeleteUsersRequest)(nil),          // 30: admin.v1.DeleteUsersRequest
	(*GetRoleListRequest)(nil),          // 31: admin.v1.GetRoleListRequest
	(*GetRoleListResponse)(nil),         // 32: admin.v1.GetRoleListResponse
	(*CreateRoleRequest)(nil),           // 33: admin.v1.CreateRoleRequest
	(*UpdateRoleRequest)(nil),           // 34: admin.v1.UpdateRoleRequest
	(*DeleteRolesRequest)(nil),          // 35: admin.v1.DeleteRolesRequest
	(*system.Permission)(nil),           // 36: system.Permission
	(*fieldmaskpb.FieldMask)(nil),       // 37: google.protobuf.FieldMask
	(*system.ButtonNode)(nil),           // 38: system.ButtonNode
	(*system.MenuNode)(nil),             // 39: system.MenuNode
	(*system.MenuRoute)(nil),            // 40: system.MenuRoute
	(*system.Menu)(nil),                 // 41: system.Menu
	(*system.User)(nil),                 // 42: system.User
	(*system.Role)(nil),                 // 43: system.Role
	(*emptypb.Empty)(nil),               // 44: google.protobuf.Empty
}
var file_admin_v1_system_proto_depIdxs = []int32{
	36, // 0: admin.v1.CreatePermissionRequest.permission:type_name -> system.Permission
	36, // 1: admin.v1.UpdatePermissionRequest.permission:type_name -> system.Permission
	37, // 2: admin.v1.UpdatePermissionRequest.update_mask:type_name -> google.protobuf.FieldMask
	36, // 3: admin.v1.GetPermissionListResponse.records:type_name -> system.Permission
	38, // 4: admin.v1.GetButtonListResponse.records:type_name -> system.ButtonNode
	37, // 5: admin.v1.UpdateRolePermissionRequest.update_mask:type_name -> google.protobuf.FieldMask
	39, // 6: admin.v1.GetMenuTreeResponse.records:type_name -> system.MenuNode
	40, // 7: admin.v1.GetUserRoutesResponse.routes:type_name -> system.MenuRoute
	40, // 8: admin.v1.GetConstantRoutesResponse.routes:type_name -> system.MenuRoute
	41, // 9: admin.v1.CreateMenuRequest.menu:type_name -> system.Menu
	41, // 10: admin.v1.UpdateMenuRequest.menu:type_name -> system.Menu
	37, // 11: admin.v1.UpdateMenuRequest.update_mask:type_name -> google.protobuf.FieldMask
	41, // 12: admin.v1.GetMenuListResponse.records:type_name -> system.Menu
	42, // 13: admin.v1.GetUserListResponse.records:type_name -> system.User
	42, // 14: admin.v1.CreateUserRequest.user:type_name -> system.User
	42, // 15: admin.v1.UpdateUserRequest.user:type_name -> system.User
	37, // 16: admin.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	43, // 17: admin.v1.GetRoleListResponse.records:type_name -> system.Role
	43, // 18: admin.v1.CreateRoleRequest.role:type_name -> system.Role
	43, // 19: admin.v1.UpdateRoleRequest.role:type_name -> system.Role
	37, // 20: admin.v1.UpdateRoleRequest.update_mask:type_name -> google.protobuf.FieldMask
	26, // 21: admin.v1.SystemService.GetUserList:input_type -> admin.v1.GetUserListRequest
	28, // 22: admin.v1.SystemService.CreateUser:input_type -> admin.v1.CreateUserRequest
	29, // 23: admin.v1.SystemService.UpdateUser:input_type -> admin.v1.UpdateUserRequest
	30, // 24: admin.v1.SystemService.DeleteUsers:input_type -> admin.v1.DeleteUsersRequest
	31, // 25: admin.v1.SystemService.GetRoleList:input_type -> admin.v1.GetRoleListRequest
	33, // 26: admin.v1.SystemService.CreateRole:input_type -> admin.v1.CreateRoleRequest
	34, // 27: admin.v1.SystemService.UpdateRole:input_type -> admin.v1.UpdateRoleRequest
	9,  // 28: admin.v1.SystemService.UpdateRolePermission:input_type -> admin.v1.UpdateRolePermissionRequest
	35, // 29: admin.v1.SystemService.DeleteRoles:input_type -> admin.v1.DeleteRolesRequest
	10, // 30: admin.v1.SystemService.GetRoleInfo:input_type -> admin.v1.GetRoleInfoRequest
	21, // 31: admin.v1.SystemService.CreateMenu:input_type -> admin.v1.CreateMenuRequest
	22, // 32: admin.v1.SystemService.UpdateMenu:input_type -> admin.v1.UpdateMenuRequest
	23, // 33: admin.v1.SystemService.DeleteMenus:input_type -> admin.v1.DeleteMenusRequest
	24, // 34: admin.v1.SystemService.GetMenuList:input_type -> admin.v1.GetMenuListRequest
	13, // 35: admin.v1.SystemService.GetPageList:input_type -> admin.v1.GetPageListRequest
	7,  // 36: admin.v1.SystemService.GetButtonList:input_type -> admin.v1.GetButtonListRequest
	11, // 37: admin.v1.SystemService.GetMenuTree:input_type -> admin.v1.GetMenuTreeRequest
	19, // 38: admin.v1.SystemService.GetConstantRoutes:input_type -> admin.v1.GetConstantRoutesRequest
	17, // 39: admin.v1.SystemService.GetUserRoutes:input_type -> admin.v1.GetUserRoutesRequest
	5,  // 40: admin.v1.SystemService.GetApiList:input_type -> admin.v1.GetApiListRequest
	0,  // 41: admin.v1.SystemService.CreatePermission:input_type -> admin.v1.CreatePermissionRequest
	1,  // 42: admin.v1.SystemService.UpdatePermission:input_type -> admin.v1.UpdatePermissionRequest
	2,  // 43: admin.v1.SystemService.DeletePermissions:input_type -> admin.v1.DeletePermissionsRequest
	3,  // 44: admin.v1.SystemService.GetPermissionList:input_type -> admin.v1.GetPermissionListRequest
	15, // 45: admin.v1.SystemService.GetVersion:input_type -> admin.v1.GetVersionRequest
	27, // 46: admin.v1.SystemService.GetUserList:output_type -> admin.v1.GetUserListResponse
	42, // 47: admin.v1.SystemService.CreateUser:output_type -> system.User
	42, // 48: admin.v1.SystemService.UpdateUser:output_type -> system.User
	44, // 49: admin.v1.SystemService.DeleteUsers:output_type -> google.protobuf.Empty
	32, // 50: admin.v1.SystemService.GetRoleList:output_type -> admin.v1.GetRoleListResponse
	43, // 51: admin.v1.SystemService.CreateRole:output_type -> system.Role
	43, // 52: admin.v1.SystemService.UpdateRole:output_type -> system.Role
	43, // 53: admin.v1.SystemService.UpdateRolePermission:output_type -> system.Role
	44, // 54: admin.v1.SystemService.DeleteRoles:output_type -> google.protobuf.Empty
	43, // 55: admin.v1.SystemService.GetRoleInfo:output_type -> system.Role
	41, // 56: admin.v1.SystemService.CreateMenu:output_type -> system.Menu
	41, // 57: admin.v1.SystemService.UpdateMenu:output_type -> system.Menu
	44, // 58: admin.v1.SystemService.DeleteMenus:output_type -> google.protobuf.Empty
	25, // 59: admin.v1.SystemService.GetMenuList:output_type -> admin.v1.GetMenuListResponse
	14, // 60: admin.v1.SystemService.GetPageList:output_type -> admin.v1.GetPageListResponse
	8,  // 61: admin.v1.SystemService.GetButtonList:output_type -> admin.v1.GetButtonListResponse
	12, // 62: admin.v1.SystemService.GetMenuTree:output_type -> admin.v1.GetMenuTreeResponse
	20, // 63: admin.v1.SystemService.GetConstantRoutes:output_type -> admin.v1.GetConstantRoutesResponse
	18, // 64: admin.v1.SystemService.GetUserRoutes:output_type -> admin.v1.GetUserRoutesResponse
	6,  // 65: admin.v1.SystemService.GetApiList:output_type -> admin.v1.GetApiListResponse
	36, // 66: admin.v1.SystemService.CreatePermission:output_type -> system.Permission
	36, // 67: admin.v1.SystemService.UpdatePermission:output_type -> system.Permission
	44, // 68: admin.v1.SystemService.DeletePermissions:output_type -> google.protobuf.Empty
	4,  // 69: admin.v1.SystemService.GetPermissionList:output_type -> admin.v1.GetPermissionListResponse
	16, // 70: admin.v1.SystemService.GetVersion:output_type -> admin.v1.GetVersionResponse
	46, // [46:71] is the sub-list for method output_type
	21, // [21:46] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_admin_v1_system_proto_init() }
func file_admin_v1_system_proto_init() {
	if File_admin_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_system_proto_rawDesc), len(file_admin_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_system_proto_goTypes,
		DependencyIndexes: file_admin_v1_system_proto_depIdxs,
		MessageInfos:      file_admin_v1_system_proto_msgTypes,
	}.Build()
	File_admin_v1_system_proto = out.File
	file_admin_v1_system_proto_goTypes = nil
	file_admin_v1_system_proto_depIdxs = nil
}
