// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin/v1/system.proto

package v1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	system "github.com/modelgate/modelgate/pkg/proto/model/system"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "admin.v1.SystemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServiceGetUserListProcedure is the fully-qualified name of the SystemService's GetUserList
	// RPC.
	SystemServiceGetUserListProcedure = "/admin.v1.SystemService/GetUserList"
	// SystemServiceCreateUserProcedure is the fully-qualified name of the SystemService's CreateUser
	// RPC.
	SystemServiceCreateUserProcedure = "/admin.v1.SystemService/CreateUser"
	// SystemServiceUpdateUserProcedure is the fully-qualified name of the SystemService's UpdateUser
	// RPC.
	SystemServiceUpdateUserProcedure = "/admin.v1.SystemService/UpdateUser"
	// SystemServiceDeleteUsersProcedure is the fully-qualified name of the SystemService's DeleteUsers
	// RPC.
	SystemServiceDeleteUsersProcedure = "/admin.v1.SystemService/DeleteUsers"
	// SystemServiceGetRoleListProcedure is the fully-qualified name of the SystemService's GetRoleList
	// RPC.
	SystemServiceGetRoleListProcedure = "/admin.v1.SystemService/GetRoleList"
	// SystemServiceCreateRoleProcedure is the fully-qualified name of the SystemService's CreateRole
	// RPC.
	SystemServiceCreateRoleProcedure = "/admin.v1.SystemService/CreateRole"
	// SystemServiceUpdateRoleProcedure is the fully-qualified name of the SystemService's UpdateRole
	// RPC.
	SystemServiceUpdateRoleProcedure = "/admin.v1.SystemService/UpdateRole"
	// SystemServiceUpdateRolePermissionProcedure is the fully-qualified name of the SystemService's
	// UpdateRolePermission RPC.
	SystemServiceUpdateRolePermissionProcedure = "/admin.v1.SystemService/UpdateRolePermission"
	// SystemServiceDeleteRolesProcedure is the fully-qualified name of the SystemService's DeleteRoles
	// RPC.
	SystemServiceDeleteRolesProcedure = "/admin.v1.SystemService/DeleteRoles"
	// SystemServiceGetRoleInfoProcedure is the fully-qualified name of the SystemService's GetRoleInfo
	// RPC.
	SystemServiceGetRoleInfoProcedure = "/admin.v1.SystemService/GetRoleInfo"
	// SystemServiceCreateMenuProcedure is the fully-qualified name of the SystemService's CreateMenu
	// RPC.
	SystemServiceCreateMenuProcedure = "/admin.v1.SystemService/CreateMenu"
	// SystemServiceUpdateMenuProcedure is the fully-qualified name of the SystemService's UpdateMenu
	// RPC.
	SystemServiceUpdateMenuProcedure = "/admin.v1.SystemService/UpdateMenu"
	// SystemServiceDeleteMenusProcedure is the fully-qualified name of the SystemService's DeleteMenus
	// RPC.
	SystemServiceDeleteMenusProcedure = "/admin.v1.SystemService/DeleteMenus"
	// SystemServiceGetMenuListProcedure is the fully-qualified name of the SystemService's GetMenuList
	// RPC.
	SystemServiceGetMenuListProcedure = "/admin.v1.SystemService/GetMenuList"
	// SystemServiceGetPageListProcedure is the fully-qualified name of the SystemService's GetPageList
	// RPC.
	SystemServiceGetPageListProcedure = "/admin.v1.SystemService/GetPageList"
	// SystemServiceGetButtonListProcedure is the fully-qualified name of the SystemService's
	// GetButtonList RPC.
	SystemServiceGetButtonListProcedure = "/admin.v1.SystemService/GetButtonList"
	// SystemServiceGetMenuTreeProcedure is the fully-qualified name of the SystemService's GetMenuTree
	// RPC.
	SystemServiceGetMenuTreeProcedure = "/admin.v1.SystemService/GetMenuTree"
	// SystemServiceGetConstantRoutesProcedure is the fully-qualified name of the SystemService's
	// GetConstantRoutes RPC.
	SystemServiceGetConstantRoutesProcedure = "/admin.v1.SystemService/GetConstantRoutes"
	// SystemServiceGetUserRoutesProcedure is the fully-qualified name of the SystemService's
	// GetUserRoutes RPC.
	SystemServiceGetUserRoutesProcedure = "/admin.v1.SystemService/GetUserRoutes"
	// SystemServiceGetApiListProcedure is the fully-qualified name of the SystemService's GetApiList
	// RPC.
	SystemServiceGetApiListProcedure = "/admin.v1.SystemService/GetApiList"
	// SystemServiceCreatePermissionProcedure is the fully-qualified name of the SystemService's
	// CreatePermission RPC.
	SystemServiceCreatePermissionProcedure = "/admin.v1.SystemService/CreatePermission"
	// SystemServiceUpdatePermissionProcedure is the fully-qualified name of the SystemService's
	// UpdatePermission RPC.
	SystemServiceUpdatePermissionProcedure = "/admin.v1.SystemService/UpdatePermission"
	// SystemServiceDeletePermissionsProcedure is the fully-qualified name of the SystemService's
	// DeletePermissions RPC.
	SystemServiceDeletePermissionsProcedure = "/admin.v1.SystemService/DeletePermissions"
	// SystemServiceGetPermissionListProcedure is the fully-qualified name of the SystemService's
	// GetPermissionList RPC.
	SystemServiceGetPermissionListProcedure = "/admin.v1.SystemService/GetPermissionList"
	// SystemServiceGetVersionProcedure is the fully-qualified name of the SystemService's GetVersion
	// RPC.
	SystemServiceGetVersionProcedure = "/admin.v1.SystemService/GetVersion"
)

// SystemServiceClient is a client for the admin.v1.SystemService service.
type SystemServiceClient interface {
	GetUserList(context.Context, *connect.Request[GetUserListRequest]) (*connect.Response[GetUserListResponse], error)
	CreateUser(context.Context, *connect.Request[CreateUserRequest]) (*connect.Response[system.User], error)
	UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[system.User], error)
	DeleteUsers(context.Context, *connect.Request[DeleteUsersRequest]) (*connect.Response[emptypb.Empty], error)
	GetRoleList(context.Context, *connect.Request[GetRoleListRequest]) (*connect.Response[GetRoleListResponse], error)
	CreateRole(context.Context, *connect.Request[CreateRoleRequest]) (*connect.Response[system.Role], error)
	UpdateRole(context.Context, *connect.Request[UpdateRoleRequest]) (*connect.Response[system.Role], error)
	UpdateRolePermission(context.Context, *connect.Request[UpdateRolePermissionRequest]) (*connect.Response[system.Role], error)
	DeleteRoles(context.Context, *connect.Request[DeleteRolesRequest]) (*connect.Response[emptypb.Empty], error)
	GetRoleInfo(context.Context, *connect.Request[GetRoleInfoRequest]) (*connect.Response[system.Role], error)
	CreateMenu(context.Context, *connect.Request[CreateMenuRequest]) (*connect.Response[system.Menu], error)
	UpdateMenu(context.Context, *connect.Request[UpdateMenuRequest]) (*connect.Response[system.Menu], error)
	DeleteMenus(context.Context, *connect.Request[DeleteMenusRequest]) (*connect.Response[emptypb.Empty], error)
	GetMenuList(context.Context, *connect.Request[GetMenuListRequest]) (*connect.Response[GetMenuListResponse], error)
	GetPageList(context.Context, *connect.Request[GetPageListRequest]) (*connect.Response[GetPageListResponse], error)
	GetButtonList(context.Context, *connect.Request[GetButtonListRequest]) (*connect.Response[GetButtonListResponse], error)
	GetMenuTree(context.Context, *connect.Request[GetMenuTreeRequest]) (*connect.Response[GetMenuTreeResponse], error)
	GetConstantRoutes(context.Context, *connect.Request[GetConstantRoutesRequest]) (*connect.Response[GetConstantRoutesResponse], error)
	GetUserRoutes(context.Context, *connect.Request[GetUserRoutesRequest]) (*connect.Response[GetUserRoutesResponse], error)
	GetApiList(context.Context, *connect.Request[GetApiListRequest]) (*connect.Response[GetApiListResponse], error)
	CreatePermission(context.Context, *connect.Request[CreatePermissionRequest]) (*connect.Response[system.Permission], error)
	UpdatePermission(context.Context, *connect.Request[UpdatePermissionRequest]) (*connect.Response[system.Permission], error)
	DeletePermissions(context.Context, *connect.Request[DeletePermissionsRequest]) (*connect.Response[emptypb.Empty], error)
	GetPermissionList(context.Context, *connect.Request[GetPermissionListRequest]) (*connect.Response[GetPermissionListResponse], error)
	GetVersion(context.Context, *connect.Request[GetVersionRequest]) (*connect.Response[GetVersionResponse], error)
}

// NewSystemServiceClient constructs a client for the admin.v1.SystemService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := File_admin_v1_system_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		getUserList: connect.NewClient[GetUserListRequest, GetUserListResponse](
			httpClient,
			baseURL+SystemServiceGetUserListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetUserList")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[CreateUserRequest, system.User](
			httpClient,
			baseURL+SystemServiceCreateUserProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[UpdateUserRequest, system.User](
			httpClient,
			baseURL+SystemServiceUpdateUserProcedure,
			connect.WithSchema(systemServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUsers: connect.NewClient[DeleteUsersRequest, emptypb.Empty](
			httpClient,
			baseURL+SystemServiceDeleteUsersProcedure,
			connect.WithSchema(systemServiceMethods.ByName("DeleteUsers")),
			connect.WithClientOptions(opts...),
		),
		getRoleList: connect.NewClient[GetRoleListRequest, GetRoleListResponse](
			httpClient,
			baseURL+SystemServiceGetRoleListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetRoleList")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[CreateRoleRequest, system.Role](
			httpClient,
			baseURL+SystemServiceCreateRoleProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[UpdateRoleRequest, system.Role](
			httpClient,
			baseURL+SystemServiceUpdateRoleProcedure,
			connect.WithSchema(systemServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRolePermission: connect.NewClient[UpdateRolePermissionRequest, system.Role](
			httpClient,
			baseURL+SystemServiceUpdateRolePermissionProcedure,
			connect.WithSchema(systemServiceMethods.ByName("UpdateRolePermission")),
			connect.WithClientOptions(opts...),
		),
		deleteRoles: connect.NewClient[DeleteRolesRequest, emptypb.Empty](
			httpClient,
			baseURL+SystemServiceDeleteRolesProcedure,
			connect.WithSchema(systemServiceMethods.ByName("DeleteRoles")),
			connect.WithClientOptions(opts...),
		),
		getRoleInfo: connect.NewClient[GetRoleInfoRequest, system.Role](
			httpClient,
			baseURL+SystemServiceGetRoleInfoProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetRoleInfo")),
			connect.WithClientOptions(opts...),
		),
		createMenu: connect.NewClient[CreateMenuRequest, system.Menu](
			httpClient,
			baseURL+SystemServiceCreateMenuProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CreateMenu")),
			connect.WithClientOptions(opts...),
		),
		updateMenu: connect.NewClient[UpdateMenuRequest, system.Menu](
			httpClient,
			baseURL+SystemServiceUpdateMenuProcedure,
			connect.WithSchema(systemServiceMethods.ByName("UpdateMenu")),
			connect.WithClientOptions(opts...),
		),
		deleteMenus: connect.NewClient[DeleteMenusRequest, emptypb.Empty](
			httpClient,
			baseURL+SystemServiceDeleteMenusProcedure,
			connect.WithSchema(systemServiceMethods.ByName("DeleteMenus")),
			connect.WithClientOptions(opts...),
		),
		getMenuList: connect.NewClient[GetMenuListRequest, GetMenuListResponse](
			httpClient,
			baseURL+SystemServiceGetMenuListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetMenuList")),
			connect.WithClientOptions(opts...),
		),
		getPageList: connect.NewClient[GetPageListRequest, GetPageListResponse](
			httpClient,
			baseURL+SystemServiceGetPageListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetPageList")),
			connect.WithClientOptions(opts...),
		),
		getButtonList: connect.NewClient[GetButtonListRequest, GetButtonListResponse](
			httpClient,
			baseURL+SystemServiceGetButtonListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetButtonList")),
			connect.WithClientOptions(opts...),
		),
		getMenuTree: connect.NewClient[GetMenuTreeRequest, GetMenuTreeResponse](
			httpClient,
			baseURL+SystemServiceGetMenuTreeProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetMenuTree")),
			connect.WithClientOptions(opts...),
		),
		getConstantRoutes: connect.NewClient[GetConstantRoutesRequest, GetConstantRoutesResponse](
			httpClient,
			baseURL+SystemServiceGetConstantRoutesProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetConstantRoutes")),
			connect.WithClientOptions(opts...),
		),
		getUserRoutes: connect.NewClient[GetUserRoutesRequest, GetUserRoutesResponse](
			httpClient,
			baseURL+SystemServiceGetUserRoutesProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetUserRoutes")),
			connect.WithClientOptions(opts...),
		),
		getApiList: connect.NewClient[GetApiListRequest, GetApiListResponse](
			httpClient,
			baseURL+SystemServiceGetApiListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetApiList")),
			connect.WithClientOptions(opts...),
		),
		createPermission: connect.NewClient[CreatePermissionRequest, system.Permission](
			httpClient,
			baseURL+SystemServiceCreatePermissionProcedure,
			connect.WithSchema(systemServiceMethods.ByName("CreatePermission")),
			connect.WithClientOptions(opts...),
		),
		updatePermission: connect.NewClient[UpdatePermissionRequest, system.Permission](
			httpClient,
			baseURL+SystemServiceUpdatePermissionProcedure,
			connect.WithSchema(systemServiceMethods.ByName("UpdatePermission")),
			connect.WithClientOptions(opts...),
		),
		deletePermissions: connect.NewClient[DeletePermissionsRequest, emptypb.Empty](
			httpClient,
			baseURL+SystemServiceDeletePermissionsProcedure,
			connect.WithSchema(systemServiceMethods.ByName("DeletePermissions")),
			connect.WithClientOptions(opts...),
		),
		getPermissionList: connect.NewClient[GetPermissionListRequest, GetPermissionListResponse](
			httpClient,
			baseURL+SystemServiceGetPermissionListProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetPermissionList")),
			connect.WithClientOptions(opts...),
		),
		getVersion: connect.NewClient[GetVersionRequest, GetVersionResponse](
			httpClient,
			baseURL+SystemServiceGetVersionProcedure,
			connect.WithSchema(systemServiceMethods.ByName("GetVersion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	getUserList          *connect.Client[GetUserListRequest, GetUserListResponse]
	createUser           *connect.Client[CreateUserRequest, system.User]
	updateUser           *connect.Client[UpdateUserRequest, system.User]
	deleteUsers          *connect.Client[DeleteUsersRequest, emptypb.Empty]
	getRoleList          *connect.Client[GetRoleListRequest, GetRoleListResponse]
	createRole           *connect.Client[CreateRoleRequest, system.Role]
	updateRole           *connect.Client[UpdateRoleRequest, system.Role]
	updateRolePermission *connect.Client[UpdateRolePermissionRequest, system.Role]
	deleteRoles          *connect.Client[DeleteRolesRequest, emptypb.Empty]
	getRoleInfo          *connect.Client[GetRoleInfoRequest, system.Role]
	createMenu           *connect.Client[CreateMenuRequest, system.Menu]
	updateMenu           *connect.Client[UpdateMenuRequest, system.Menu]
	deleteMenus          *connect.Client[DeleteMenusRequest, emptypb.Empty]
	getMenuList          *connect.Client[GetMenuListRequest, GetMenuListResponse]
	getPageList          *connect.Client[GetPageListRequest, GetPageListResponse]
	getButtonList        *connect.Client[GetButtonListRequest, GetButtonListResponse]
	getMenuTree          *connect.Client[GetMenuTreeRequest, GetMenuTreeResponse]
	getConstantRoutes    *connect.Client[GetConstantRoutesRequest, GetConstantRoutesResponse]
	getUserRoutes        *connect.Client[GetUserRoutesRequest, GetUserRoutesResponse]
	getApiList           *connect.Client[GetApiListRequest, GetApiListResponse]
	createPermission     *connect.Client[CreatePermissionRequest, system.Permission]
	updatePermission     *connect.Client[UpdatePermissionRequest, system.Permission]
	deletePermissions    *connect.Client[DeletePermissionsRequest, emptypb.Empty]
	getPermissionList    *connect.Client[GetPermissionListRequest, GetPermissionListResponse]
	getVersion           *connect.Client[GetVersionRequest, GetVersionResponse]
}

// GetUserList calls admin.v1.SystemService.GetUserList.
func (c *systemServiceClient) GetUserList(ctx context.Context, req *connect.Request[GetUserListRequest]) (*connect.Response[GetUserListResponse], error) {
	return c.getUserList.CallUnary(ctx, req)
}

// CreateUser calls admin.v1.SystemService.CreateUser.
func (c *systemServiceClient) CreateUser(ctx context.Context, req *connect.Request[CreateUserRequest]) (*connect.Response[system.User], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUser calls admin.v1.SystemService.UpdateUser.
func (c *systemServiceClient) UpdateUser(ctx context.Context, req *connect.Request[UpdateUserRequest]) (*connect.Response[system.User], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUsers calls admin.v1.SystemService.DeleteUsers.
func (c *systemServiceClient) DeleteUsers(ctx context.Context, req *connect.Request[DeleteUsersRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteUsers.CallUnary(ctx, req)
}

// GetRoleList calls admin.v1.SystemService.GetRoleList.
func (c *systemServiceClient) GetRoleList(ctx context.Context, req *connect.Request[GetRoleListRequest]) (*connect.Response[GetRoleListResponse], error) {
	return c.getRoleList.CallUnary(ctx, req)
}

// CreateRole calls admin.v1.SystemService.CreateRole.
func (c *systemServiceClient) CreateRole(ctx context.Context, req *connect.Request[CreateRoleRequest]) (*connect.Response[system.Role], error) {
	return c.createRole.CallUnary(ctx, req)
}

// UpdateRole calls admin.v1.SystemService.UpdateRole.
func (c *systemServiceClient) UpdateRole(ctx context.Context, req *connect.Request[UpdateRoleRequest]) (*connect.Response[system.Role], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// UpdateRolePermission calls admin.v1.SystemService.UpdateRolePermission.
func (c *systemServiceClient) UpdateRolePermission(ctx context.Context, req *connect.Request[UpdateRolePermissionRequest]) (*connect.Response[system.Role], error) {
	return c.updateRolePermission.CallUnary(ctx, req)
}

// DeleteRoles calls admin.v1.SystemService.DeleteRoles.
func (c *systemServiceClient) DeleteRoles(ctx context.Context, req *connect.Request[DeleteRolesRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteRoles.CallUnary(ctx, req)
}

// GetRoleInfo calls admin.v1.SystemService.GetRoleInfo.
func (c *systemServiceClient) GetRoleInfo(ctx context.Context, req *connect.Request[GetRoleInfoRequest]) (*connect.Response[system.Role], error) {
	return c.getRoleInfo.CallUnary(ctx, req)
}

// CreateMenu calls admin.v1.SystemService.CreateMenu.
func (c *systemServiceClient) CreateMenu(ctx context.Context, req *connect.Request[CreateMenuRequest]) (*connect.Response[system.Menu], error) {
	return c.createMenu.CallUnary(ctx, req)
}

// UpdateMenu calls admin.v1.SystemService.UpdateMenu.
func (c *systemServiceClient) UpdateMenu(ctx context.Context, req *connect.Request[UpdateMenuRequest]) (*connect.Response[system.Menu], error) {
	return c.updateMenu.CallUnary(ctx, req)
}

// DeleteMenus calls admin.v1.SystemService.DeleteMenus.
func (c *systemServiceClient) DeleteMenus(ctx context.Context, req *connect.Request[DeleteMenusRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteMenus.CallUnary(ctx, req)
}

// GetMenuList calls admin.v1.SystemService.GetMenuList.
func (c *systemServiceClient) GetMenuList(ctx context.Context, req *connect.Request[GetMenuListRequest]) (*connect.Response[GetMenuListResponse], error) {
	return c.getMenuList.CallUnary(ctx, req)
}

// GetPageList calls admin.v1.SystemService.GetPageList.
func (c *systemServiceClient) GetPageList(ctx context.Context, req *connect.Request[GetPageListRequest]) (*connect.Response[GetPageListResponse], error) {
	return c.getPageList.CallUnary(ctx, req)
}

// GetButtonList calls admin.v1.SystemService.GetButtonList.
func (c *systemServiceClient) GetButtonList(ctx context.Context, req *connect.Request[GetButtonListRequest]) (*connect.Response[GetButtonListResponse], error) {
	return c.getButtonList.CallUnary(ctx, req)
}

// GetMenuTree calls admin.v1.SystemService.GetMenuTree.
func (c *systemServiceClient) GetMenuTree(ctx context.Context, req *connect.Request[GetMenuTreeRequest]) (*connect.Response[GetMenuTreeResponse], error) {
	return c.getMenuTree.CallUnary(ctx, req)
}

// GetConstantRoutes calls admin.v1.SystemService.GetConstantRoutes.
func (c *systemServiceClient) GetConstantRoutes(ctx context.Context, req *connect.Request[GetConstantRoutesRequest]) (*connect.Response[GetConstantRoutesResponse], error) {
	return c.getConstantRoutes.CallUnary(ctx, req)
}

// GetUserRoutes calls admin.v1.SystemService.GetUserRoutes.
func (c *systemServiceClient) GetUserRoutes(ctx context.Context, req *connect.Request[GetUserRoutesRequest]) (*connect.Response[GetUserRoutesResponse], error) {
	return c.getUserRoutes.CallUnary(ctx, req)
}

// GetApiList calls admin.v1.SystemService.GetApiList.
func (c *systemServiceClient) GetApiList(ctx context.Context, req *connect.Request[GetApiListRequest]) (*connect.Response[GetApiListResponse], error) {
	return c.getApiList.CallUnary(ctx, req)
}

// CreatePermission calls admin.v1.SystemService.CreatePermission.
func (c *systemServiceClient) CreatePermission(ctx context.Context, req *connect.Request[CreatePermissionRequest]) (*connect.Response[system.Permission], error) {
	return c.createPermission.CallUnary(ctx, req)
}

// UpdatePermission calls admin.v1.SystemService.UpdatePermission.
func (c *systemServiceClient) UpdatePermission(ctx context.Context, req *connect.Request[UpdatePermissionRequest]) (*connect.Response[system.Permission], error) {
	return c.updatePermission.CallUnary(ctx, req)
}

// DeletePermissions calls admin.v1.SystemService.DeletePermissions.
func (c *systemServiceClient) DeletePermissions(ctx context.Context, req *connect.Request[DeletePermissionsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePermissions.CallUnary(ctx, req)
}

// GetPermissionList calls admin.v1.SystemService.GetPermissionList.
func (c *systemServiceClient) GetPermissionList(ctx context.Context, req *connect.Request[GetPermissionListRequest]) (*connect.Response[GetPermissionListResponse], error) {
	return c.getPermissionList.CallUnary(ctx, req)
}

// GetVersion calls admin.v1.SystemService.GetVersion.
func (c *systemServiceClient) GetVersion(ctx context.Context, req *connect.Request[GetVersionRequest]) (*connect.Response[GetVersionResponse], error) {
	return c.getVersion.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the admin.v1.SystemService service.
type SystemServiceHandler interface {
	GetUserList(context.Context, *connect.Request[GetUserListRequest]) (*connect.Response[GetUserListResponse], error)
	CreateUser(context.Context, *connect.Request[CreateUserRequest]) (*connect.Response[system.User], error)
	UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[system.User], error)
	DeleteUsers(context.Context, *connect.Request[DeleteUsersRequest]) (*connect.Response[emptypb.Empty], error)
	GetRoleList(context.Context, *connect.Request[GetRoleListRequest]) (*connect.Response[GetRoleListResponse], error)
	CreateRole(context.Context, *connect.Request[CreateRoleRequest]) (*connect.Response[system.Role], error)
	UpdateRole(context.Context, *connect.Request[UpdateRoleRequest]) (*connect.Response[system.Role], error)
	UpdateRolePermission(context.Context, *connect.Request[UpdateRolePermissionRequest]) (*connect.Response[system.Role], error)
	DeleteRoles(context.Context, *connect.Request[DeleteRolesRequest]) (*connect.Response[emptypb.Empty], error)
	GetRoleInfo(context.Context, *connect.Request[GetRoleInfoRequest]) (*connect.Response[system.Role], error)
	CreateMenu(context.Context, *connect.Request[CreateMenuRequest]) (*connect.Response[system.Menu], error)
	UpdateMenu(context.Context, *connect.Request[UpdateMenuRequest]) (*connect.Response[system.Menu], error)
	DeleteMenus(context.Context, *connect.Request[DeleteMenusRequest]) (*connect.Response[emptypb.Empty], error)
	GetMenuList(context.Context, *connect.Request[GetMenuListRequest]) (*connect.Response[GetMenuListResponse], error)
	GetPageList(context.Context, *connect.Request[GetPageListRequest]) (*connect.Response[GetPageListResponse], error)
	GetButtonList(context.Context, *connect.Request[GetButtonListRequest]) (*connect.Response[GetButtonListResponse], error)
	GetMenuTree(context.Context, *connect.Request[GetMenuTreeRequest]) (*connect.Response[GetMenuTreeResponse], error)
	GetConstantRoutes(context.Context, *connect.Request[GetConstantRoutesRequest]) (*connect.Response[GetConstantRoutesResponse], error)
	GetUserRoutes(context.Context, *connect.Request[GetUserRoutesRequest]) (*connect.Response[GetUserRoutesResponse], error)
	GetApiList(context.Context, *connect.Request[GetApiListRequest]) (*connect.Response[GetApiListResponse], error)
	CreatePermission(context.Context, *connect.Request[CreatePermissionRequest]) (*connect.Response[system.Permission], error)
	UpdatePermission(context.Context, *connect.Request[UpdatePermissionRequest]) (*connect.Response[system.Permission], error)
	DeletePermissions(context.Context, *connect.Request[DeletePermissionsRequest]) (*connect.Response[emptypb.Empty], error)
	GetPermissionList(context.Context, *connect.Request[GetPermissionListRequest]) (*connect.Response[GetPermissionListResponse], error)
	GetVersion(context.Context, *connect.Request[GetVersionRequest]) (*connect.Response[GetVersionResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := File_admin_v1_system_proto.Services().ByName("SystemService").Methods()
	systemServiceGetUserListHandler := connect.NewUnaryHandler(
		SystemServiceGetUserListProcedure,
		svc.GetUserList,
		connect.WithSchema(systemServiceMethods.ByName("GetUserList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceCreateUserHandler := connect.NewUnaryHandler(
		SystemServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(systemServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceUpdateUserHandler := connect.NewUnaryHandler(
		SystemServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(systemServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceDeleteUsersHandler := connect.NewUnaryHandler(
		SystemServiceDeleteUsersProcedure,
		svc.DeleteUsers,
		connect.WithSchema(systemServiceMethods.ByName("DeleteUsers")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetRoleListHandler := connect.NewUnaryHandler(
		SystemServiceGetRoleListProcedure,
		svc.GetRoleList,
		connect.WithSchema(systemServiceMethods.ByName("GetRoleList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceCreateRoleHandler := connect.NewUnaryHandler(
		SystemServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(systemServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceUpdateRoleHandler := connect.NewUnaryHandler(
		SystemServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(systemServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceUpdateRolePermissionHandler := connect.NewUnaryHandler(
		SystemServiceUpdateRolePermissionProcedure,
		svc.UpdateRolePermission,
		connect.WithSchema(systemServiceMethods.ByName("UpdateRolePermission")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceDeleteRolesHandler := connect.NewUnaryHandler(
		SystemServiceDeleteRolesProcedure,
		svc.DeleteRoles,
		connect.WithSchema(systemServiceMethods.ByName("DeleteRoles")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetRoleInfoHandler := connect.NewUnaryHandler(
		SystemServiceGetRoleInfoProcedure,
		svc.GetRoleInfo,
		connect.WithSchema(systemServiceMethods.ByName("GetRoleInfo")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceCreateMenuHandler := connect.NewUnaryHandler(
		SystemServiceCreateMenuProcedure,
		svc.CreateMenu,
		connect.WithSchema(systemServiceMethods.ByName("CreateMenu")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceUpdateMenuHandler := connect.NewUnaryHandler(
		SystemServiceUpdateMenuProcedure,
		svc.UpdateMenu,
		connect.WithSchema(systemServiceMethods.ByName("UpdateMenu")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceDeleteMenusHandler := connect.NewUnaryHandler(
		SystemServiceDeleteMenusProcedure,
		svc.DeleteMenus,
		connect.WithSchema(systemServiceMethods.ByName("DeleteMenus")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetMenuListHandler := connect.NewUnaryHandler(
		SystemServiceGetMenuListProcedure,
		svc.GetMenuList,
		connect.WithSchema(systemServiceMethods.ByName("GetMenuList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetPageListHandler := connect.NewUnaryHandler(
		SystemServiceGetPageListProcedure,
		svc.GetPageList,
		connect.WithSchema(systemServiceMethods.ByName("GetPageList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetButtonListHandler := connect.NewUnaryHandler(
		SystemServiceGetButtonListProcedure,
		svc.GetButtonList,
		connect.WithSchema(systemServiceMethods.ByName("GetButtonList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetMenuTreeHandler := connect.NewUnaryHandler(
		SystemServiceGetMenuTreeProcedure,
		svc.GetMenuTree,
		connect.WithSchema(systemServiceMethods.ByName("GetMenuTree")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetConstantRoutesHandler := connect.NewUnaryHandler(
		SystemServiceGetConstantRoutesProcedure,
		svc.GetConstantRoutes,
		connect.WithSchema(systemServiceMethods.ByName("GetConstantRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetUserRoutesHandler := connect.NewUnaryHandler(
		SystemServiceGetUserRoutesProcedure,
		svc.GetUserRoutes,
		connect.WithSchema(systemServiceMethods.ByName("GetUserRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetApiListHandler := connect.NewUnaryHandler(
		SystemServiceGetApiListProcedure,
		svc.GetApiList,
		connect.WithSchema(systemServiceMethods.ByName("GetApiList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceCreatePermissionHandler := connect.NewUnaryHandler(
		SystemServiceCreatePermissionProcedure,
		svc.CreatePermission,
		connect.WithSchema(systemServiceMethods.ByName("CreatePermission")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceUpdatePermissionHandler := connect.NewUnaryHandler(
		SystemServiceUpdatePermissionProcedure,
		svc.UpdatePermission,
		connect.WithSchema(systemServiceMethods.ByName("UpdatePermission")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceDeletePermissionsHandler := connect.NewUnaryHandler(
		SystemServiceDeletePermissionsProcedure,
		svc.DeletePermissions,
		connect.WithSchema(systemServiceMethods.ByName("DeletePermissions")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetPermissionListHandler := connect.NewUnaryHandler(
		SystemServiceGetPermissionListProcedure,
		svc.GetPermissionList,
		connect.WithSchema(systemServiceMethods.ByName("GetPermissionList")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceGetVersionHandler := connect.NewUnaryHandler(
		SystemServiceGetVersionProcedure,
		svc.GetVersion,
		connect.WithSchema(systemServiceMethods.ByName("GetVersion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admin.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServiceGetUserListProcedure:
			systemServiceGetUserListHandler.ServeHTTP(w, r)
		case SystemServiceCreateUserProcedure:
			systemServiceCreateUserHandler.ServeHTTP(w, r)
		case SystemServiceUpdateUserProcedure:
			systemServiceUpdateUserHandler.ServeHTTP(w, r)
		case SystemServiceDeleteUsersProcedure:
			systemServiceDeleteUsersHandler.ServeHTTP(w, r)
		case SystemServiceGetRoleListProcedure:
			systemServiceGetRoleListHandler.ServeHTTP(w, r)
		case SystemServiceCreateRoleProcedure:
			systemServiceCreateRoleHandler.ServeHTTP(w, r)
		case SystemServiceUpdateRoleProcedure:
			systemServiceUpdateRoleHandler.ServeHTTP(w, r)
		case SystemServiceUpdateRolePermissionProcedure:
			systemServiceUpdateRolePermissionHandler.ServeHTTP(w, r)
		case SystemServiceDeleteRolesProcedure:
			systemServiceDeleteRolesHandler.ServeHTTP(w, r)
		case SystemServiceGetRoleInfoProcedure:
			systemServiceGetRoleInfoHandler.ServeHTTP(w, r)
		case SystemServiceCreateMenuProcedure:
			systemServiceCreateMenuHandler.ServeHTTP(w, r)
		case SystemServiceUpdateMenuProcedure:
			systemServiceUpdateMenuHandler.ServeHTTP(w, r)
		case SystemServiceDeleteMenusProcedure:
			systemServiceDeleteMenusHandler.ServeHTTP(w, r)
		case SystemServiceGetMenuListProcedure:
			systemServiceGetMenuListHandler.ServeHTTP(w, r)
		case SystemServiceGetPageListProcedure:
			systemServiceGetPageListHandler.ServeHTTP(w, r)
		case SystemServiceGetButtonListProcedure:
			systemServiceGetButtonListHandler.ServeHTTP(w, r)
		case SystemServiceGetMenuTreeProcedure:
			systemServiceGetMenuTreeHandler.ServeHTTP(w, r)
		case SystemServiceGetConstantRoutesProcedure:
			systemServiceGetConstantRoutesHandler.ServeHTTP(w, r)
		case SystemServiceGetUserRoutesProcedure:
			systemServiceGetUserRoutesHandler.ServeHTTP(w, r)
		case SystemServiceGetApiListProcedure:
			systemServiceGetApiListHandler.ServeHTTP(w, r)
		case SystemServiceCreatePermissionProcedure:
			systemServiceCreatePermissionHandler.ServeHTTP(w, r)
		case SystemServiceUpdatePermissionProcedure:
			systemServiceUpdatePermissionHandler.ServeHTTP(w, r)
		case SystemServiceDeletePermissionsProcedure:
			systemServiceDeletePermissionsHandler.ServeHTTP(w, r)
		case SystemServiceGetPermissionListProcedure:
			systemServiceGetPermissionListHandler.ServeHTTP(w, r)
		case SystemServiceGetVersionProcedure:
			systemServiceGetVersionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) GetUserList(context.Context, *connect.Request[GetUserListRequest]) (*connect.Response[GetUserListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetUserList is not implemented"))
}

func (UnimplementedSystemServiceHandler) CreateUser(context.Context, *connect.Request[CreateUserRequest]) (*connect.Response[system.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.CreateUser is not implemented"))
}

func (UnimplementedSystemServiceHandler) UpdateUser(context.Context, *connect.Request[UpdateUserRequest]) (*connect.Response[system.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.UpdateUser is not implemented"))
}

func (UnimplementedSystemServiceHandler) DeleteUsers(context.Context, *connect.Request[DeleteUsersRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.DeleteUsers is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetRoleList(context.Context, *connect.Request[GetRoleListRequest]) (*connect.Response[GetRoleListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetRoleList is not implemented"))
}

func (UnimplementedSystemServiceHandler) CreateRole(context.Context, *connect.Request[CreateRoleRequest]) (*connect.Response[system.Role], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.CreateRole is not implemented"))
}

func (UnimplementedSystemServiceHandler) UpdateRole(context.Context, *connect.Request[UpdateRoleRequest]) (*connect.Response[system.Role], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.UpdateRole is not implemented"))
}

func (UnimplementedSystemServiceHandler) UpdateRolePermission(context.Context, *connect.Request[UpdateRolePermissionRequest]) (*connect.Response[system.Role], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.UpdateRolePermission is not implemented"))
}

func (UnimplementedSystemServiceHandler) DeleteRoles(context.Context, *connect.Request[DeleteRolesRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.DeleteRoles is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetRoleInfo(context.Context, *connect.Request[GetRoleInfoRequest]) (*connect.Response[system.Role], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetRoleInfo is not implemented"))
}

func (UnimplementedSystemServiceHandler) CreateMenu(context.Context, *connect.Request[CreateMenuRequest]) (*connect.Response[system.Menu], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.CreateMenu is not implemented"))
}

func (UnimplementedSystemServiceHandler) UpdateMenu(context.Context, *connect.Request[UpdateMenuRequest]) (*connect.Response[system.Menu], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.UpdateMenu is not implemented"))
}

func (UnimplementedSystemServiceHandler) DeleteMenus(context.Context, *connect.Request[DeleteMenusRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.DeleteMenus is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetMenuList(context.Context, *connect.Request[GetMenuListRequest]) (*connect.Response[GetMenuListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetMenuList is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetPageList(context.Context, *connect.Request[GetPageListRequest]) (*connect.Response[GetPageListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetPageList is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetButtonList(context.Context, *connect.Request[GetButtonListRequest]) (*connect.Response[GetButtonListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetButtonList is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetMenuTree(context.Context, *connect.Request[GetMenuTreeRequest]) (*connect.Response[GetMenuTreeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetMenuTree is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetConstantRoutes(context.Context, *connect.Request[GetConstantRoutesRequest]) (*connect.Response[GetConstantRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetConstantRoutes is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetUserRoutes(context.Context, *connect.Request[GetUserRoutesRequest]) (*connect.Response[GetUserRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetUserRoutes is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetApiList(context.Context, *connect.Request[GetApiListRequest]) (*connect.Response[GetApiListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetApiList is not implemented"))
}

func (UnimplementedSystemServiceHandler) CreatePermission(context.Context, *connect.Request[CreatePermissionRequest]) (*connect.Response[system.Permission], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.CreatePermission is not implemented"))
}

func (UnimplementedSystemServiceHandler) UpdatePermission(context.Context, *connect.Request[UpdatePermissionRequest]) (*connect.Response[system.Permission], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.UpdatePermission is not implemented"))
}

func (UnimplementedSystemServiceHandler) DeletePermissions(context.Context, *connect.Request[DeletePermissionsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.DeletePermissions is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetPermissionList(context.Context, *connect.Request[GetPermissionListRequest]) (*connect.Response[GetPermissionListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetPermissionList is not implemented"))
}

func (UnimplementedSystemServiceHandler) GetVersion(context.Context, *connect.Request[GetVersionRequest]) (*connect.Response[GetVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.SystemService.GetVersion is not implemented"))
}
